### ISSUE TITLE
Fonts are distributed as datafiles

### ISSUE THREAD

**Issue by eaburns** [gonum/plot#107]
Original [issue 80](https://code.google.com/p/plotinum/issues/detail?id=80) created by eaburns on 2012-09-20T16:12:32.000Z:

If Plotinum is included with a program than that binary cannot be distributed to machines without the Plotinum source.

A possible solution to this is to embed the data files into the Plotinum source.  This may violate some GPL stuff, however...

**Comment by kortschak** [comment]
There is a possibility that Nigel Tao's new shiny repo might be able to help here - there is a font package that looks to provide font rendering.

**Comment by sbinet** [comment]
actually, according to: 
 https://en.wikipedia.org/wiki/GPL_font_exception
 http://www.gnu.org/licenses/gpl-faq.html#FontException
if a font is distributed under GPL+FE (ie: GPL with the Font Exception) one can redistribute it w/o having to distribute the s/w as GPL.
I think. (I am not a lawyer, though)

according to:
 https://www.freedesktop.org/wiki/Software/Fonts/
it should be safe (again, IANAL) to use SIL/OFL based fonts.

I'd propose to use Redhat's Liberation fonts:
 https://fedorahosted.org/liberation-fonts/
 http://www.redhat.com/en/about/blog/liberation-fonts

LWN has an interesting article about this issue:
 https://lwn.net/Articles/409813/

I can send a PR with a CL using Liberation-2.00.1, if you want.

**Comment by eaburns** [comment]
> The Liberation(tm) Fonts is a font family which aims at metric compatibility with Arial, Times New Roman, and Courier New.

Perfect! This is what I have been looking for for years. Please do send a pull request. However, let's be mindful of binary size when embedding data files like this.

**Comment by sbinet** [comment]
it is indeed a bit heavy on the size:

```sh
$> ll
total 4.0M
-rw-r--r-- 1 binet binet  242 Oct  4  2012 AUTHORS
-rw-r--r-- 1 binet binet  806 Oct  4  2012 ChangeLog
-rw-r--r-- 1 binet binet 272K Oct  4  2012 LiberationMono-BoldItalic.ttf
-rw-r--r-- 1 binet binet 295K Oct  4  2012 LiberationMono-Bold.ttf
-rw-r--r-- 1 binet binet 269K Oct  4  2012 LiberationMono-Italic.ttf
-rw-r--r-- 1 binet binet 307K Oct  4  2012 LiberationMono-Regular.ttf
-rw-r--r-- 1 binet binet 342K Oct  4  2012 LiberationSans-BoldItalic.ttf
-rw-r--r-- 1 binet binet 346K Oct  4  2012 LiberationSans-Bold.ttf
-rw-r--r-- 1 binet binet 348K Oct  4  2012 LiberationSans-Italic.ttf
-rw-r--r-- 1 binet binet 342K Oct  4  2012 LiberationSans-Regular.ttf
-rw-r--r-- 1 binet binet 363K Oct  4  2012 LiberationSerif-BoldItalic.ttf
-rw-r--r-- 1 binet binet 357K Oct  4  2012 LiberationSerif-Bold.ttf
-rw-r--r-- 1 binet binet 363K Oct  4  2012 LiberationSerif-Italic.ttf
-rw-r--r-- 1 binet binet 380K Oct  4  2012 LiberationSerif-Regular.ttf
-rw-r--r-- 1 binet binet 4.4K Oct  4  2012 LICENSE
-rw-r--r-- 1 binet binet 2.0K Oct  4  2012 README
-rw-r--r-- 1 binet binet  350 Oct  4  2012 TODO

$> du -hs .
4.0M	.
```

**Comment by eaburns** [comment]
Does gzip help or are they already compressed?

**Comment by sbinet** [comment]
right. compressed, it's north of 2Mb (2232k)
see: https://fedorahosted.org/releases/l/i/liberation-fonts/liberation-fonts-ttf-2.00.1.tar.gz

IIRC, go-bindata has an option to embed *and* compress.

**Comment by eaburns** [comment]
I just built plotutil/main.go and it's 7.4M. Maybe 2M is OK. Also, the tar.gz file there has a couple of extra fonts that we don't need. Let's see. Also, does anyone else have an opinion on this? Missing font data files has been a constant source of confusion and bug reports ever since I announced Plotinum. I'd love to fix it.

**Comment by sbinet** [comment]
I see you are having fun w/ https://github.com/golang/go/issues/14885.
do you still want me to send a PR with the removal of Nimbus and the addition of a `go generate` friendly script to embed the Liberation fonts ?

**Comment by eaburns** [comment]
Yes. That CL is unrelated to any of this, though it may be useful in the distant future (when x/image/font supports truetype fonts).
