### ISSUE TITLE
plot: make Rect work the same way as image.Rectangle

### ISSUE THREAD

**Issue by kortschak** [gonum/plot#13]
image.Rectangle keeps to points, Min and Max and calculates Size from those. plot.Rect keeps a Min and a Size and calculates Max from those. It would be nice to have the two types speak with a similar accent.

Raised [here](https://github.com/sbinet/gonum-plot/commit/6c810295adb4dd7fa1233526d7a4b35f9f69de6f#commitcomment-9691115).

**Comment by kortschak** [comment]
Also possibly consider Rect -> Rectangle for similar though less pressing reasons.

**Comment by eaburns** [comment]
I choose min and size because it elides the min>max issue that the other
representation has... though I guess that assume size is non-negative.

**Comment by kortschak** [comment]
I figured that was the reason.

> though I guess that assume size is non-negative.

If we were in uint* space that would be OK. I think the comment in image covers this: if Min > Max we don't guarantee anything.

**Comment by eaburns** [comment]
I'm OK with the change. Consistency is good. But I'm not convinced there is
much more of an advantage than that. Is there?

**Comment by kortschak** [comment]
None.

**Comment by sbinet** [comment]
consistency with `image.Rectangle` is good.
"self-consistency" and good "code flow" is even better :)
as hinted above, I always second guess myself (is `Min` or `Max` the method? or the field?)
count me as +1 on this.
