### ISSUE TITLE
Drawing legends outside of the plot

### ISSUE THREAD

**Issue by eaburns** [gonum/plot#133]
Original [issue 106](https://code.google.com/p/plotinum/issues/detail?id=106) created by eaburns on 2012-12-12T13:54:08.000Z:

Currently legends only draw in the data area of the plot.  Often this is just great, but sometimes it is very frustrating because the legend can get in the way.  Either, there should be support to save the legend to a separate image, or support to squish the data area of the plot and draw the legend outside in the same image.

**Comment by peterbourgon** [comment]
Is there a way to do this currently, by e.g. toying around with the canvas?

**Comment by ctessum** [comment]
Yes! See [here](https://godoc.org/gonum.org/v1/plot/plotter#HeatMap).

This issue can probably be closed now if there isn't any objection.
