### ISSUE TITLE
OpenGL back-end for vg

### ISSUE THREAD

**Issue by eaburns** [gonum/plot#137]
Original [issue 110](https://code.google.com/p/plotinum/issues/detail?id=110) created by eaburns on 2013-02-13T16:46:54.000Z:

This should be pretty easy, but I am not sure of a great way to do dashed lines in OpenGL, maybe someone with shader experience [Steve] could figure it out.

An OpenGL back-end would make it much easier to make a quality GUI front-end for Plotinum---something that has been requested a few times at this point.

**Comment by sbinet** [comment]
I agree.

**Comment by sbinet** [comment]
closed by https://github.com/gonum/plot/pull/646
