### ISSUE TITLE
Add vg length constants

### ISSUE THREAD

**Issue by eaburns** [gonum/plot#144]
Original [issue 117](https://code.google.com/p/plotinum/issues/detail?id=117) created by eaburns on 2013-02-22T13:45:15.000Z:

This would mimic time.Second and such:

vg.Inch
vg.Centimeter

Used like this:

len := 5*vg.Inch

The current vg.Inches() and friends would have to stick around to avoid breaking the API.

**Comment by sbinet** [comment]
fixed by #9
