### ISSUE TITLE
Properly deal alpha-pre-multiplied colors in vgsvg.

### ISSUE THREAD

**Issue by eaburns** [gonum/plot#157]
Original [issue 130](https://code.google.com/p/plotinum/issues/detail?id=130) created by eaburns on 2013-06-28T12:10:46.000Z:

color.RGBA returns alpha-pre-multiplied values, but SVG wants non-pre-multiplied values, so we have to convert.

**Comment by kortschak** [comment]
This is fixed by 1511f12123bb5412a4f92eedab0537410a6b6a88.

**Comment by eaburns** [comment]
This must have been an issue that was partially uploaded when the import hit a rate limit. Sorry for not catching it.
