### ISSUE TITLE
Port wiki pages over from code.google.com/p/plotinum

### ISSUE THREAD

**Issue by eaburns** [gonum/plot#177]
This is probably useful: https://code.google.com/p/support-tools/wiki/WikiToMarkdownTool

**Comment by kortschak** [comment]
I'm having a look at this now. Are we wanting to keep all the revisions? This won't do that without scripting.

**Comment by kortschak** [comment]
I have the tip converted and modified to point to the correct imports. I can put that state up with the view to getting the code correct w.r.t. changes to the API that may have broken the examples. I'll wait for your go-ahead.

**Comment by eaburns** [comment]
Thanks, Dan! Sounds great. Personally, I don't care about the history here, just converting the docs is good enough.

Could you figure out how to upload them to github? I was about to convert them, but the only way I could find to do the upload was copy and paste. It seemed tedious, so I didn't do it.

Also, when I did the conversion it still linked to images on Google code. I'm not sure if those are sticking around (maybe they are, I honestly don't know). If we think they are going away, we should figure out a place to put them too. But we have time, so it's no rush at the moment.

**Comment by eaburns** [comment]
To be clear: go ahead!

**Comment by kortschak** [comment]
Cheers. I've been editing, so copy/paste is fine.

**Comment by eaburns** [comment]
Thanks, Dan.
