### ISSUE TITLE
Plot sets all axis ticks to zero

### ISSUE THREAD

**Issue by btracey** [gonum/plot#209]
Sample code: http://play.golang.org/p/r7ijwebIq1

The X axis plots fine, while the y axis labels are all zero. There is variation in the first significant digit of the Y axis, so it should be able to plot even though the actual value is small .

**Comment by kortschak** [comment]
precisionOf needs to get the abs of x before calculating the log of x.

**Comment by btracey** [comment]
Yep, that fixes it. PR coming.

**Comment by kortschak** [comment]
*ping*

**Comment by btracey** [comment]
Isn't this fixed? https://github.com/gonum/plot/blob/master/axis.go#L516 has an Abs in it.

**Comment by kortschak** [comment]
OK, so we can close this then.

**Comment by kortschak** [comment]
Fixed via #210.
