### ISSUE TITLE
Examples do not actually work

### ISSUE THREAD

**Issue by esantoro** [gonum/plot#212]
I am playing with the example from: 

   https://github.com/gonum/plot/wiki/Drawing-to-an-Image-or-Writer:-How-to-save-a-plot-to-an-image.Image-or-an-io.Writer,-not-a-file.

The line:

        c := vgimg.NewImage(img)

Does not work, becuse there is no NewImage(...) in the vgimg package.

**Comment by kortschak** [comment]
Please take another look.

**Comment by esantoro** [comment]
Just took another look. There is not vgimg.NewImage function. Please, take a look you too.

**Comment by kortschak** [comment]
I edited the wiki and checked the code by running it locally - it is correct. You were not wrong in your first post; it is fixed.
