### ISSUE TITLE
draw2d upstream change

### ISSUE THREAD

**Issue by brettowe** [gonum/plot#214]
vgimg is broken currently without the below change

```
--- github.com/gonum/plot/vg/vgimg/vgimg.go.old	2015-08-15 13:49:34.049328696 -0700
+++ github.com/gonum/plot/vg/vgimg/vgimg.go	2015-08-15 13:49:37.186032505 -0700
@@ -18,6 +18,7 @@
 	"io"
 
 	"github.com/llgcode/draw2d"
+	"github.com/llgcode/draw2d/draw2dimg"
 	"golang.org/x/image/tiff"
 
 	"github.com/gonum/plot/vg"
@@ -92,7 +93,7 @@
 	}
 	if c.gc == nil {
 		h := float64(c.img.Bounds().Max.Y - c.img.Bounds().Min.Y)
-		c.gc = draw2d.NewGraphicContext(c.img)
+		c.gc = draw2dimg.NewGraphicContext(c.img)
 		c.gc.SetDPI(c.dpi)
 		c.gc.Scale(1, -1)
 		c.gc.Translate(0, -h)
```

**Comment by kortschak** [comment]
This was a result of https://github.com/llgcode/draw2d/pull/72.

**Comment by eaburns** [comment]
This isn't the first breaking change from upstream. Is it time to vendor?

**Comment by eaburns** [comment]
Also, thanks for finding this and for the quick fix!

**Comment by kortschak** [comment]
Wait until 1.5 and use GO15VENDOREXPERIMENT? Do we know that no side effects or types leak from downstream via our imports?

**Comment by eaburns** [comment]
I'm not sure, but does it matter? We stated that we may break downstream until this coming Jan. Right?

**Comment by kortschak** [comment]
Yeah, not fussed about that. I am just concerned about importing "repo/package" as "vendor/repo/package" that has a side-effect that clients will have problems with if they import as "repo/package". I doubt there will be, but you're more likely to know.

**Comment by eaburns** [comment]
I see. How annoying. I guess we should avoid vendoring then. Since this is a library, that's the official recommendation anyway.

**Comment by llgcode** [comment]
sorry for the API change. But how do you manage API change and release?

**Comment by brettowe** [comment]
doesn't go have a way to choose a version in the import line now?
if so then its just a matter of doing a 'release' every so often

**Comment by kortschak** [comment]
Version pinning is done by vendoring, but as mentioned above is frowned on in libraries because there may be negative impacts ranging from code bloat up to inconsistent state resulting in incorrect behaviour - in this case I would think it's likely the former, but we'd need to do an assessment. If llg.draw2d is stabilising then things should be fine.

@llgcode We are also in a state of API flux; we have a goal to have a stable API by the beginning of next year.

**Comment by brettowe** [comment]
I think I had read about this: http://labix.org/gopkg.in
and thought it was part of go itself

**Comment by llgcode** [comment]
@kortschak 
We don't have any milestone for stabilizing now. But we want to have a clean API that support new back-end pdf and svg. So we need to converge. The problem is releasing API with go tool. Sorry but I miss something with the concept of "vendoring".

**Comment by kortschak** [comment]
@brettowe Yes, we would only be able to do that with downstream that have opted in to gopkg.in. Aside, as a group gonum have not discussed whether we should use it for our packages, but personally I would rather not.

@llgcode Which aspect, the notion of [vendoring itself](https://github.com/golang/go/commit/183cc0cd41f06f83cb7a2490a499e3f9101befff) or the problems that arise with vendoring in non-main packages?

**Comment by llgcode** [comment]
Yes the notion of vendoring. But now it's clear. thanks

-- Laurent.
