### ISSUE TITLE
Fix Google Code imports

### ISSUE THREAD

**Issue by pbdeuchler** [gonum/plot#217]
Please fix your `code.google.com` imports (this should have been part of the Go 1.5 release as per the Go team release notes on import paths :wink: ). 

[These](https://github.com/gonum/plot/blob/d0e5470f385cd918b9e96c2f2cc98620dbf60c2b/vg/vgx11/painter.go#L31) [lines](https://github.com/gonum/plot/blob/d0e5470f385cd918b9e96c2f2cc98620dbf60c2b/vg/font.go#L21) make it impossible to `go get` the library and almost impossibly difficult to use due to the ridiculous shenanigans one has to do in order to rewrite import paths

**Comment by kortschak** [comment]
This is #216 and more complicated than simply changing imports.
