### ISSUE TITLE
Split the vg package in it's own repo

### ISSUE THREAD

**Issue by yohcop** [gonum/plot#233]
The github.com/gonum/plot/vg package is super useful outside of gonum/plot to generate drawings that can be rendered in svg, png, pdf, etc.

It seems ok to import gonum/plot in a project and then only use the vg interfaces directly, but since it's not the "official" use for this package, it's not always clear how stable the API is going to be.

Splitting this package in say gonum/vg would also force the api and code to be well designed, encapsulated, etc.

Thanks!

**Comment by eaburns** [comment]
I don't think that it needs to be moved to get these benefits. One can import it without importing any of the other plot packages already. It's in no way internal, and that was international. Once the plot API is locked down, vg should be included in that guarantee.

However, you make a valid observation that more time could be spent too better define the vg interface. I've always felt that it was at best slightly under-documented. Maybe we should open a separate issue for that. I recommend closing this one. What do others think?

**Comment by yohcop** [comment]
I don't feel strongly either way. Like I said i think the vg api is really useful in itself, and it _seemed_ ok to just use the vg package, even if it feels a bit internal (only because it's part of a bigger package). But as long as you say it was designed this way intentionally, I think it's ok.

Feel free to close/reopen a different issue as you see fit!

**Comment by eaburns** [comment]
I'm glad that you find it useful! Please feel free to open issues here if you have other suggestions.

I'll let others make the final decision about this one.

**Comment by eaburns** [comment]
I'm going to close this for now. Rest assured that we intend vg to be externally usable and stable (at least that was always my intention). If the API can be improved in any way---and I'm certain that it can--- please feel free to file issues or send PRs for it.
