### ISSUE TITLE
plot: ability to display 2 (or n) connected plots

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#239]
it should be possible to display multiple plots on the same canvas (or gather multiple canvases on the same image?).
it should also be possible to "connect" the axes of these plots so they are properly aligned:

http://matplotlib.org/examples/axes_grid/simple_axesgrid.html
http://matplotlib.org/examples/axes_grid/simple_axesgrid2.html
http://matplotlib.org/examples/pylab_examples/axes_zoom_effect.html
http://matplotlib.org/examples/pylab_examples/finance_work2.html
http://matplotlib.org/examples/pylab_examples/ganged_plots.html
http://matplotlib.org/examples/pylab_examples/scatter_hist.html
http://matplotlib.org/examples/pylab_examples/subplots_demo.html

**Comment by eaburns** [comment]
Also, see #151.

**Comment by sbinet** [comment]
ah, sorry. my queries on the gonum-plot issue tracker failed me.

**Comment by sbinet** [comment]
@ebusato

**Comment by ctessum** [comment]
Closed via #354.
