### ISSUE TITLE
vg/draw: rename into vg/vgdraw ?

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#246]
hi,

I was toying with `gonum/plot` and `golang.org/x/exp/shiny`:
 https://gist.github.com/sbinet/2d3226e3f5e00e41a2e7
(hit 'n' to generate a new plot, 'r' to refresh, 'q' or ESC to quit)

unfortunately, `vg/draw` conflicts with `image/draw`.
perhaps we should just bite the bullet and rename `vg/draw` into `vg/vgdraw` ? the stuttering is minimal (and there is the precedent of `vg/vgimg`...)

**Comment by eaburns** [comment]
No. Let's not worsen our package names due to possible import conflicts. The name can be changed at import time by the importer.

See Effective Go:

> And don't worry about collisions a priori. The package name is only the default name for imports; it need not be unique across all source code, and in the rare case of a collision the importing package can choose a different name to use locally.

https://golang.org/doc/effective_go.html#package-names

**Comment by sbinet** [comment]
of course, but it is a bit inconvenient with `goimports`...
