### ISSUE TITLE
plotter: general_test.go overwrites expected golden images with failure result

### ISSUE THREAD

**Issue by kortschak** [gonum/plot#251]
This should not happen unless requested. Either do nothing without request or write to a `*_fail.ext` file for each failure (probably on request).

**Comment by kortschak** [comment]
Ach. Sorry. This is my misreading of the code's intention. It does the behaviour I suggest above, but names the files `*_golden.ext`. I think this could be changed to fail rather then golden, since they are tarnished.

**Comment by kortschak** [comment]
Arrrgh even more. I don't like what it's doing, but it is correct.

**Comment by eaburns** [comment]
Feel free to open another bug to remind us to fix it. It could also be a good intro bug if someone new wants to start helping out.
