### ISSUE TITLE
plotutils.AddLines stores names in a map which causes legend ordering issues

### ISSUE THREAD

**Issue by skiesel** [gonum/plot#268]
https://github.com/gonum/plot/blob/master/plotutil/add.go#L179

When calling plotutils.AddLines the names passed in get stored temporarily in a map which causes the legend ordering to get mixed up. When creating multiple plots it can be important to have the lines/glyphs matched up and in the same order across all plots. If this was a slice instead of a map the order would be preserved.

**Comment by skiesel** [comment]
Looks like this happens for many of the add utility functions actually.

**Comment by sbinet** [comment]
looking into it.

**Comment by sbinet** [comment]
please give it a spin.

**Comment by skiesel** [comment]
Looks good on my end. Thanks!
