### ISSUE TITLE
travis: enable tests for go-1.7-beta

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#279]
we should enable travis-tests with go-tip (the release-to-be 1.7)
this would catch comparisons errors as noted in #278 (_ie_ the different compression algorithms)

**Comment by jonlawlor** [comment]
There isn't a beta release for 1.7 yet.  Previously we've waited for one before adding it to the build matrix, but I think it is possible to build against tip using the `gimme` command.  It wouldn't produce stable results though.

**Comment by sbinet** [comment]
right. well, the beta is quite close.
I suppose it's fine to wait for it.

**Comment by btracey** [comment]
We used to enable tip, but it turned out the failure rate was quite high. This made it hard on our own end to ensure correctness, and so the last cycle we only started testing at the beta.

**Comment by ctessum** [comment]
Closing via #349.
