### ISSUE TITLE
Heatmap xmin and ymin incorrect for negative minimum values

### ISSUE THREAD

**Issue by jasonpfox** [gonum/plot#289]
Given Y(0) == -19 and Y(1) == -18, ymin comes out as -0.5, where it needs to be -19.5.  Looks like scale for xmin and ymin only worked correctly for min endpoint at 0.

**Comment by jasonpfox** [comment]
I am trying to push up a fix in a branch but it looks like I don't have permission to gonum/plot...

**Comment by sbinet** [comment]
yep, you don't.
the normal workflow on github is to fork, fix/enhance your fork and then send a pull request (a PR) against the original project.

**Comment by sbinet** [comment]
see how I did it there: https://github.com/sbinet/gonum-plot/tree/time-loc
(ie a branch `time-loc` on my fork of `gonum/plot` in `sbinet/gonum-plot`)

which a PR'ed here: `https://github.com/gonum/plot/pull/278`

having said that, could you show us what you tried, what `git` told you and what's the output of `git remote -v` ?

**Comment by jasonpfox** [comment]
I was to push up a new branch with the change via SourceTree:

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags --set-upstream origin 289-HeatmapXminYmin:289-HeatmapXminYmin
remote: Permission to gonum/plot.git denied to jasonpfox.

fatal: unable to access 'https://github.com/gonum/plot/': The requested URL returned error: 403
Pushing to https://github.com/gonum/plot

**Comment by kortschak** [comment]
Use github to make the fork. I can see that you don't have a fork of gonum/plot in your repos there. Then pull to your local from that repo, make changes, push back to your github repo, then send the PR.

**Comment by kortschak** [comment]
Would you please send a reproducer. The description here is not complete enough for me to write a fix.

**Comment by kortschak** [comment]
Note that Contour uses the same logic for the domain calculations, so any fix should probably be applied there too.

**Comment by jasonpfox** [comment]
I submitted a pull request with a fix.  Also looked briefly at contour.  The first fix is not applicable, but the second (line 172 in contour.go change the +0.5 to -0.5 in finding index into pal) I believe would apply.  I did not include that in submission since I was not setup to create or test that code.  This is also likely not as noticeable or problematic with contour lines as it is with heatmaps

**Comment by kortschak** [comment]
I'll send a PR for the contour palette fix. Thanks.

**Comment by kortschak** [comment]
I've just checked and the ps calculation in contour is correct, and I'm not convinced the scaling for the heatmap is wrong either. I will try to get your reproducer working.

**Comment by kortschak** [comment]
Yes. The issue with the palette is a bug in palette, not here. I'll send a PR for that.

**Comment by kortschak** [comment]
The issue is a floating point error in the calculation of the hue steps in palette.Rainbow. I have a fix, but it highlights that you are using probably more colour graduations than are strictly necessary.
