### ISSUE TITLE
Tick label are indisintinguishable for small differences

### ISSUE THREAD

**Issue by jasonpfox** [gonum/plot#301]
Current precision requirement for tick values allows resolving min and max tick values, but does not provide ability to resolve differences between adjacent tick values when when they are close spaced.  Note all tick labels on colorbar heatmap exactly equal at 0.0002

![tickprecisionambiguity](https://cloud.githubusercontent.com/assets/17184422/16923799/272f17e6-4cea-11e6-9697-b64b5308ef01.png)

**Comment by kortschak** [comment]
In future, please also post a minimal reproducer. This makes writing the tests easier (this doesn't need anything except a basic plot and an axis).

**Comment by jasonpfox** [comment]
Reproduce by:

import (
	"log"

	"github.com/gonum/plot"
	"github.com/gonum/plot/palette"
	"github.com/gonum/plot/plotter"
)

type LowDR struct {
	c, r int
}

func (l LowDR) Dims() (int, int) {
	return l.c, l.r
}

func (l LowDR) X(c int) float64 {
	return .005 + float64(c)*1e-5
}

func (l LowDR) Y(r int) float64 {
	return .005 + float64(r)*1e-5
}

func (l LowDR) Z(c, r int) float64 {
	return float64(c) + 10.0*float64(r)
}

func main() {
	x := LowDR{c: 5, r: 5}
	h := plotter.NewHeatMap(x, palette.Heat(50, 1))

	p, err := plot.New()
	if err != nil {
		log.Panic(err)
	}
	p.Title.Text = "Tick Label Precision Test"

	p.Add(h)

	err = p.Save(500, 500, "smallDRAxis.png")
	if err != nil {
		log.Panic(err)
	}

}

![smalldraxisambiguous](https://cloud.githubusercontent.com/assets/17184422/16936532/5b57f89e-4d35-11e6-9f21-44701ee37901.png)
![smalldraxisfixed](https://cloud.githubusercontent.com/assets/17184422/16936535/6028a080-4d35-11e6-8af4-ba6572e52626.png)

**Comment by kortschak** [comment]
Minimal reproducer:

```
package main

import (
	"log"

	"github.com/gonum/plot"
	"github.com/gonum/plot/plotter"
)

func main() {
	p, err := plot.New()
	if err != nil {
		log.Fatal(err)
	}

	s, err := plotter.NewScatter(plotter.XYs{{0.00012, 0.00012}})
	if err != nil {
		log.Fatal(err)
	}

	p.Add(s)
	p.X.Min = 0.00010
	p.X.Max = 0.00015

	err = p.Save(500, 500, "issue301.png")
	if err != nil {
		log.Fatalf("failed to save: %v", err)
	}
}
```

**Comment by jasonpfox** [comment]
That is a simpler reproducer... :)
