### ISSUE TITLE
plot/vg: consider using Go-font for fonts

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#326]
more details here: https://blog.golang.org/go-fonts

(the advantage would be license. but we should probably check whether it fits `gonum/plot` rendering wrt PS)

**Comment by eaburns** [comment]
The blog post said that they are mostly metric equivalent, so it should work. Let's try it.

**Comment by sbinet** [comment]
hum... not sure the gofonts have everything we want:

```go
    FontMap = map[string]string{
		"Courier":             "GoMono-Regular",
		"Courier-Bold":        "GoMono-Bold",
		"Courier-Oblique":     "GoMono-Italic",
		"Courier-BoldOblique": "GoMono-BoldItalic",

		"Helvetica":             "GoSans-Regular",
		"Helvetica-Bold":        "GoSans-Bold",
		"Helvetica-Oblique":     "GoSans-Italic",
		"Helvetica-BoldOblique": "GoSans-BoldItalic",

		"Times-Roman":      "GoSerif-Regular",
		"Times-Bold":       "GoSerif-Bold",
		"Times-Italic":     "GoSerif-Italic",
		"Times-BoldItalic": "GoSerif-BoldItalic",
    }
```

`GoMono-xyz` is, obviously, `"golang.org/x/image/font/gofont/gomono{,bold,bolditalic,italic}"`

`GoSans-xyz` is *probably*, `"golang.org/x/image/font/gofont/go{regular,bold,bolditalic,italic}"`

but what about the `GoSerif-xyz` ones?

**Comment by eaburns** [comment]
Yeah, hm, those have no match. :-(

**Comment by sbinet** [comment]
I've filed https://github.com/golang/go/issues/17964

**Comment by sbinet** [comment]
FYI, I have started to gather a few interesting fonts here:
- https://github.com/go-fonts

namely:
- https://github.com/go-fonts/liberation
- https://github.com/go-fonts/latin-modern (what most LaTeX installations use)
- https://github.com/go-fonts/stix (what matplotlib uses)
- https://github.com/go-fonts/dejavu

**Comment by sbinet** [comment]
we're using `go-fonts/liberation` by default, now.
