### ISSUE TITLE
Stacked bars and negative values

### ISSUE THREAD

**Issue by neclepsio** [gonum/plot#338]
Stacked bars don't work with negative values.

For example, from the following code I expect the red bar going under the horizontal axis, then the blue and green above.

```
package main

import (
	"github.com/gonum/plot"
	"github.com/gonum/plot/plotter"
	"github.com/gonum/plot/plotutil"
	"github.com/gonum/plot/vg"
)

func main() {
	groupA := plotter.Values{-20, -35, -30, -35, -27}
	groupB := plotter.Values{25, 32, 34, 20, 25}
	groupC := plotter.Values{12, 28, 15, 21, 8}

	p, err := plot.New()
	if err != nil {
		panic(err)
	}
	p.Title.Text = "Bar chart"
	p.Y.Label.Text = "Heights"

	w := vg.Points(20)

	barsA, err := plotter.NewBarChart(groupA, w)
	if err != nil {
		panic(err)
	}
	barsA.LineStyle.Width = vg.Length(0)
	barsA.Color = plotutil.Color(0)
	barsA.Offset = -w

	barsB, err := plotter.NewBarChart(groupB, w)
	if err != nil {
		panic(err)
	}
	barsB.LineStyle.Width = vg.Length(0)
	barsB.Color = plotutil.Color(1)

	barsC, err := plotter.NewBarChart(groupC, w)
	if err != nil {
		panic(err)
	}
	barsC.LineStyle.Width = vg.Length(0)
	barsC.Color = plotutil.Color(2)
	barsC.Offset = w

	barsB.StackOn(barsA)
	barsC.StackOn(barsB)

	p.Add(barsA, barsB, barsC)
	p.Legend.Add("Group A", barsA)
	p.Legend.Add("Group B", barsB)
	p.Legend.Add("Group C", barsC)
	p.Legend.Top = true
	p.NominalX("One", "Two", "Three", "Four", "Five")

	if err := p.Save(5*vg.Inch, 3*vg.Inch, "barchart.png"); err != nil {
		panic(err)
	}
}
```

Also, you should test with negative groupB values.

**Comment by kortschak** [comment]
What behaviour are you expecting? I can't imagine any sensible graphical interpretation of stacking negative values.

**Comment by neclepsio** [comment]
In my case, I have to represent how the hours of work are spent. For example: on the bottom, the hours spent in each month for maintainance on product 1, 2 and 3. On the top, the hours spent for development of new products 4 and 5.

So the first impression shows how much new development and maintenance is done each month, but you can also see the the detail for each product.

I already do that using plotly.js (https://plot.ly/javascript/bar-charts/#bar-chart-with-relative-barmode), but I'm looking for a server side replacement.

**Comment by kortschak** [comment]
That approach with plotly for this use using sign looks like an abuse - obviously hinted by the fact that you would see negative time spent on products 4 and 5. What you really want is to be able to have one sub-plot pointing upwards for the maintenance products and one facing down for the new development products. We can do the sub-plots, and if we can't do downwards facing that can be an issue.

Adding the capacity to handle mixed signs I think is an error in design. What the plotly plot does is not a signed sum, it is an offset unsigned sum. Further the ordering of bar components varies between factors dependent on the sign of elements; this is something that makes plots harder to read. I don't think we should handle mixed sign and probably should return an error or panic if they exist.

**Comment by ctessum** [comment]
Although I'm also not convinced that the use case above is an appropriate use of this type of plot, I think there are some valid use cases. One example is [here](http://www.pnas.org/content/111/52/18490/F3.expansion.html). I imagine it would be possible to do this without making any changes to the plotter itself, but instead just by separating the positive and negative numbers into seperate plotters. This could perhaps be done as a package example.

**Comment by kortschak** [comment]
With the addition of a sum marker, it become meaningful, though note that that figure still allows reordering of elements within a factor which adds cognitive clutter (though with only two elements this is not huge - and could have been fixed by the author).

**Comment by ctessum** [comment]
The example is here: https://godoc.org/github.com/gonum/plot/plotter#BarChart.

I think this can be closed now. If there is still an issue perhaps create another issue.
