### ISSUE TITLE
plot/plotter: add an example for LogScales

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#355]
we should probably add an example on how to make a plot with a nice log-scale.

**Comment by DavidGamba** [comment]
Should this example make it to the wiki: https://github.com/gonum/plot/wiki/Example-plots ? I usually look there for examples on what can be done, I didn't know to look for them in https://github.com/gonum/plot/tree/master/plotter

Thanks!

**Comment by sbinet** [comment]
@DavidGamba perhaps a better place (rather than the `plotter` directory) would be godoc: https://godoc.org/github.com/gonum/plot/plotter#pkg-examples

but it's true we should have a nice gallery of plots, like https://matplotlib.org/gallery.html

I vaguely recall @ctessum talking about this at some point.
but we need:
 - a nice gallery website
 - (perhaps) a way to extract examples from `gonum/plot/...` and push them on this gallery
 - a way to execute and test these gallery plots.

(ah! that's gonum/plot#118)

**Comment by sbinet** [comment]
an alternative that I use for my [hplot](https://go-hep.org/x/hep/hplot) package is to put the plot examples (together with the output image) on the README page:
 https://github.com/go-hep/hep/tree/master/hplot#tiles-of-1d-histograms

- the images are linked from the repository reference images
- the code is automatically extracted from the `ExampleFooBar` function (with [embedmd](https://github.com/campoy/embedmd))

**Comment by ctessum** [comment]
@DavidGamba @sbinet here is what I was talking about: https://ctessum.github.io/gonum.github.io/

It's still a little buggy but the idea is that the examples are automatically extracted from the source code, presented as full programs for people that are not familiar with how go namespaces work, and are editable/runnable.
