### ISSUE TITLE
gonum.org/v1/gonum/floats returns 404?

### ISSUE THREAD

**Issue by gyuho** [gonum/plot#368]
Hello,

Is `gonum.org` as import path down now?

```
go get -d -v gonum.org/v1/gonum/floats
Fetching https://gonum.org/v1/gonum/floats?go-get=1
Parsing meta tags from https://gonum.org/v1/gonum/floats?go-get=1 (status code 404)
get "gonum.org/v1/gonum/floats": found meta tag main.metaImport{Prefix:"gonum.org/v1/gonum", VCS:"git", RepoRoot:"https://github.com/gonum/gonum"} at https://gonum.org/v1/gonum/floats?go-get=1
get "gonum.org/v1/gonum/floats": verifying non-authoritative meta tag
Fetching https://gonum.org/v1/gonum?go-get=1
Parsing meta tags from https://gonum.org/v1/gonum?go-get=1 (status code 404)
gonum.org/v1/gonum (download)
```

This seems to work, but when I try to vendor this with glide, 

```
[WARN]	Unable to checkout gonum.org/v1/gonum
[ERROR]	Error looking for gonum.org/v1/gonum/floats: https://gonum.org/v1/gonum Not Found
```

Should I report to `glide`?

Thanks!

Other project does not return 404:

```
go get -v -d -u github.com/mattn/goreman
github.com/mattn/goreman (download)
github.com/daviddengcn/go-colortext (download)
github.com/joho/godotenv (download)
Fetching https://gopkg.in/yaml.v2?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag main.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
```

**Comment by btracey** [comment]
I just ran `go get -u -t gonum.org/v1/gonum/floats` on my machine and it worked fine. I haven't worked with glide, and am not sure how to fix.

**Comment by gyuho** [comment]
@btracey Do you get `https://gonum.org/v1/gonum?go-get=1 (status code 404)`? If not, maybe just me.

**Comment by btracey** [comment]
Yes, I get that. The web page doesn't actually exist, so I would expect it to 404

**Comment by gyuho** [comment]
Ok then seems like glide issue. Thanks!

**Comment by sbinet** [comment]
BTW, wouldn't it be convenient to redirect to the godoc page for the package one tries to access when coming from a browser?
See, e.g.: https://go-hep.org/x/hep/hbook

**Comment by btracey** [comment]
It would. Pull requests accepted :-)

**Comment by sbinet** [comment]
done: gonum/gonum.github.io#4

**Comment by shenwei356** [comment]
Right now I solve this manually:

```
go get -u github.com/gonum/floats
cd $GOPATH/src
mkdir -p gonum.org/v1
ln -s gonum.org/v1/gonum github.com/gonum

**Comment by sbinet** [comment]
@shenwei356 you shouldn't do that.
`gonum.org/v1/gonum/floats` and `github.com/gonum/floats` are not the same thing (not even necessarily the same code)
