### ISSUE TITLE
all: migrate import paths to gonum.org/v1/plot

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#372]
as discussed elsewhere [ref needed], we want to migrate the import path of `github.com/gonum/plot` to `gonum.org/v1/plot`.

contrary to the migration of `github.com/gonum/{matrix,stat,...}` to `gonum.org/v1/gonum/{mat,stat,...}` this can't be done w/o breaking people importing `github.com/gonum/plot`.

the fix is easy though:

```
$> find $GOPATH/src/github.com/me/pkg \
  -type f \
  -exec sed -i -e 's|"github.com/gonum/plot|"gonum.org/v1/plot|g' {} \;
```

**Comment by sbinet** [comment]
@gonum/developers do we want to pull the trigger on this?

**Comment by kortschak** [comment]
I am ready for this, but I think we need a quorum.

**Comment by btracey** [comment]
I'm ready for this (though I'm less important in the `plot` repo)

**Comment by vladimir-ch** [comment]
I'm also ready for this (though I'm even less important in the plot repo)

**Comment by ctessum** [comment]
Works for me.

**Comment by sbinet** [comment]
the vanity import path isn't yet enforced in the PR gonum/plot#374.
we could give some migration time before doing so (and merging the final PR)

**Comment by kortschak** [comment]
Set a date (Monday next week?) and do it then.

**Comment by sbinet** [comment]
ok:

- ~now: announce the plan below (to `golang-nuts`, `slack#data-science` and `gonum-dev`)
- 2017/08/14: merge in `#374`
- 2017/08/21: merge another PR that enforces the vanity import path

**Comment by sbinet** [comment]
forgot about that tool:

```
$> go get -u golang.org/x/tools/cmd/fiximports
$> fiximports -replace "github.com/gonum/plot=gonum.org/v1/plot"  ./...
```

(won't change comments, nor `README.md` though...)
