### ISSUE TITLE
vg/vgpdf: switch to a backend that supports font embedding

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#389]
we should (probably) consider switching away from `bitbucket.org/zombiezen/gopdf/pdf` that isn't maintained much.

and probably switch to `github.com/jung-kurt/gofpdf`.

4 reasons:

- it is maintained
- it is stable
- it is on github (so we don't require a mercurial client)
- it supports fonts embedding

the last one is a rather nice feature and allows for better PDF compatibility (w/o relying on fonts metrics being the exact same than the `Courier`, `Helvetica` and `Times` ones.)

**Comment by sbinet** [comment]
@eaburns @kortschak do you agree ?

**Comment by eaburns** [comment]
Yes, this sounds like a great change.
