### ISSUE TITLE
plot: "gonum.org/v1/gonum/floats" is imported

### ISSUE THREAD

**Issue by kortschak** [gonum/plot#390]
We have gonum proper separate from plot to prevent people needing to get all of gonum just to plot, but axis.go imports floats.

This is for the `Round` function and will be fixed by #388.

**Comment by btracey** [comment]
Looks like this is closed?

**Comment by kortschak** [comment]
Yes, probably. I suspect that #388 will be at least partially reverted, but the `Round` use will be guarded.
