### ISSUE TITLE
axis: Incorrect positioning of tick marks new scheme

### ISSUE THREAD

**Issue by decibelcooper** [gonum/plot#393]
Starting with commit e7f526d68a91a8b21c225cdbbbd8662d53c541f4, there is a problem with positioning and/or labeling of tick marks.  The new scheme rounds tick labels, but the tick marks do not move to reflect this.  The code _could_ be changed to move the tick marks to reflect the labels, but this would ruin the regular tick mark positioning.  I believe it fundamentally does not make sense to round the tick marks and/or labels.

The problem is exemplified by this plot generated before and after the commit in question (using the [go-hep.org hplot package](https://github.com/go-hep/hep/tree/master/hplot) which in-turn uses gonum plot), where 
the peak on the y axis is ideally 3.096:
## Before
![before](https://user-images.githubusercontent.com/13596458/31231574-dec6c2c6-a9ac-11e7-861a-2d9a4102ec11.png)
## After
![after](https://user-images.githubusercontent.com/13596458/31231711-3dec86be-a9ad-11e7-9fec-e983278c6592.png)

One can see that in the After case, the vertical tick labels misrepresent the position of the peak.

**Comment by kortschak** [comment]
I want to change the algorithm to use `string` (actually `[]byte`) uniqueness rather than `float64` uniqueness. This would change the output of the after case by modifying the lowest tick to 3.0. This partially addresses your issue since by convention the number of displayed decimal places indicates the intended precision of a value, so under that scheme the plot remains accurate - to the displayed precision.

A second PR could add a minimum precision attribute to axis ticks, defaulting to 0 which would use the lowest possible precision to attain unique labels. There are problems with this approach, but they only present themselves when people are attempting to get more out of their data than exists (i.e. they are expecting variance over precision that is not present).

>I believe it fundamentally does not make sense to round the tick marks and/or labels.

This is untenable because of the way float values represent real numbers. If there is not rounding (in some sense) of labels then for some series you end up with long labels that impact on plot presentation.

**Comment by decibelcooper** [comment]
> This is untenable because of the way float values represent real numbers. If there is not rounding (in some sense) of labels then for some series you end up with long labels that impact on plot presentation.

The point that you seem to be missing is that tick marks should not be chosen to be something with a long decimal representation in the first place.  In _any_ case where the tick marks are chosen to be something that must be rounded in order to present a sane level of precision, the label will misrepresent the tick mark.  Again, the problem of long labels should be addressed from the point of choosing the tick mark positions, not from rounding labels.

**Comment by ctessum** [comment]
As Dan said, not all numbers are able to be precisely represented by
float64s, so rounding has to occur at some point if we don't want to plot
labels like "2.999999999999997", for instance.

**Comment by decibelcooper** [comment]
> As Dan said, not all numbers are able to be precisely represented by
float64s, so rounding has to occur at some point if we don't want to plot
labels like "2.999999999999997", for instance.

I agree that one should not put such a label on a tick mark (except in extreme circumstances).  However, your statement that "rounding" is the solution is incorrect, IMO.

What I'm saying is that no tick mark should be placed at 2.999999999999997 on the axis (except in extreme cases).  Let's imagine that your plot ranges from 2.9 to 3.0, and you have a tick mark at 2.95.  Should you then round the label to say "3.0"?  No.  That would clearly misrepresent the tick mark.  You would think: 'How is that tick mark labeled "3.0" when it is clearly precisely in the middle of the plot?'  The problem is that the tick mark has far higher precision on the graph than its label.

The solution is to avoid choosing tick mark locations that cause such a conflict.  Each tick mark should be placed such that its label implies infinite precision.  In the scenario I just mentioned, if only two significant figures are allowed, then tick marks should only be placed at 2.9000000000000 and 3.000000000000, which put the tick marks at the limits of the axis in that case, and the labels could simply be "2.9" and "3.0".

**Comment by decibelcooper** [comment]
In the above comment, I mention twice that such long labels should not be placed except in extreme circumstances.  Let me give an extreme circumstance.

suppose you have an axis with a range 2.999999999999997 to 3.000000000000000.  In this case, what should your labels be?  Well, in this case there is no choice but to specify many digits.  Rounding is still not an option.  Please see below how ROOT (CERN) handles the case were the limits are 2.999999 to 3.000000:
![asdf](https://user-images.githubusercontent.com/13596458/31258013-f98cdf8e-a9f0-11e7-8858-a7d043b485ae.png)

Obviously having such long labels is not ideal.  However, there is no other option, because rounding is not one of them.

**Comment by kortschak** [comment]
@decibelcooper in the case of the code as it exists, ticks *are* moved slightly if there is rounding since the tick value is rounded, and rounding *only* occurs in order to minimise the level of precision to what is required to ensure unique labels. TBH, I cannot see what you have a problem with in the original post. Can you explain it to me so I can understand better?

**Comment by decibelcooper** [comment]
> in the case of the code as it exists, ticks are moved slightly if there is rounding since the tick value is rounded

As far as I can tell, this is statement is not correct.  Please note that in the lines https://github.com/gonum/plot/blob/e7f526d68a91a8b21c225cdbbbd8662d53c541f4/axis.go#L391-L393, the tick Values are taken as the elements of `labels` (unrounded), while the labels are taken as the formatted elements of `newLabels` (rounded).

Let us say for the sake of argument that the "After" plot above has labels 3.0, 3.1, and 3.2.  From what you are saying, it seems that you would be happy with this, correct?

There is, however, a very big problem with this plot.  The "Before" and "After" plots are identical except for the code that determines the labels.  Take a look at each plot and make an estimate for the peak (most blue) projected on the y axis.  The estimates will not agree, because one implements rounding.

> Also, I have to say that I would not accept a plot like the one ROOT produces (for the same reason that I don't like our 3, 3.1, 3.2 - it should be 3.0, 3.1, 3.2).

Perhaps this is at the root (no pun intended) of our disagreement.  I suppose I just have one more thing to say.  I would not accept a plot like the "After" case above.  IMO, it is wrong.  I very regrettably cannot use this library unless there is at least an option to disable the rounding.

**Comment by ctessum** [comment]
@decibelcooper the code you link to is part of a method of `DefaultTicks`,
which I believe is the default tick creator but can be swapped out for a
custom one, such as `LogTicks` below it. Would you be willing to create an
alternate implementation of the `Ticker` interface that fixes the problem
as you see it? It could then be considered as a replacement for
`DefaultTicks`, but if that is not agreed upon then at least you would have
something that works for you and others with the same preferences.

**Comment by decibelcooper** [comment]
@ctessum,

This is a good suggestion, thank you.  I can indeed make an alternative and submit a PR.

**Comment by kortschak** [comment]
>As far as I can tell, this is statement is not correct.

Yes, I corrected the comment before your post.

>Let us say for the sake of argument that the "After" plot above has labels 3.0, 3.1, and 3.2. From what you are saying, it seems that you would be happy with this, correct?

Yes (with an epsilon; I am not sure about the whether the ticks should be shifted).

>There is, however, a very big problem with this plot. The "Before" and "After" plots are identical except for the code that determines the labels. Take a look at each plot and make an estimate for the peak (most blue) projected on the y axis. The estimates will not agree, because one implements rounding.

I have two problems with this position:

1. The position of the tick is accurate to the level of rounding. Perhaps we could do better in allowing users to specify the minimum precision - and display to that precision or better.

2. A plot is not a place to estimate a value from.

>Perhaps this is at the root (no pun intended) of our disagreement. I suppose I just have one more thing to say. I would not accept a plot like the "After" case above. IMO, it is wrong. I very regrettably cannot use this library unless there is at least an option to disable the rounding.

All plots are wrong because all plots round to a degree - there is no such thing as infinite precision in the real world. We just make that explicit - as do many fields - although I think we could improve on that level of explicitness.

I would be very happy to see a PR that helps improve the behaviour we have.

**Comment by kortschak** [comment]
@decibelcooper can you post a reproducer of the heatmap in the original post so I can play with changing the tick alignment. Thanks.

**Comment by eaburns** [comment]
Maybe I'm misunderstanding, but it looks to me like David has a point. On
the line they linked (
https://github.com/gonum/plot/blob/e7f526d68a91a8b21c225cdbbbd8662d53c541f4/axis.go#L392),
we set `Tick.Value` to `v`, and `Tick.Label` to `formatFloat(newLabels[j],
-1)`. Why are we setting the location of the tick (`Tick.Value`) to
anything other than the float from which we generated the label?

**Comment by decibelcooper** [comment]
The above PR resolves my issue.  Having done this, let me explain a couple things.

1. The statements that Dan and others have said, that at some point rounding must occur because of the way floats are represented, I now understand to be true.  This was not something I understood, and I apologize for not getting there sooner.
2. I have identified the main cause of the problem.  On lines https://github.com/gonum/plot/blob/50336e281717e5f1685e3c611828dfb42c82cf66/axis.go#L367-L372, there is an implicit assumption that `n` must be greater than or equal to the suggested number of ticks in order to proceed.  Instead, I believe it is accurate to say that `n` must be greater than or equal to the suggested number less one.  This is because for 3 required major ticks, there are only 2 intervals between them.
3. I have resolved the issue conceded in 1. in a different, less aggressive way.  From the max major tick value and the tick interval, I infer the level of precision required for the labels, and pass this on to the format function.

**Comment by decibelcooper** [comment]
Here is an example of the AltTicks ticker compared to the previously shown "Before" and "After", where "After" refers to the current DefaultTicks.

## Before
![before](https://user-images.githubusercontent.com/13596458/31231574-dec6c2c6-a9ac-11e7-861a-2d9a4102ec11.png)
## After (current DefaultTicks)
![after](https://user-images.githubusercontent.com/13596458/31231711-3dec86be-a9ad-11e7-9fec-e983278c6592.png)
## AltTicks
![jpsireconfromtracks2d 1](https://user-images.githubusercontent.com/13596458/31290939-f3486078-aa93-11e7-8a82-2a19d261e2d4.png)

**Comment by decibelcooper** [comment]
> @decibelcooper can you post a reproducer of the heatmap in the original post so I can play with changing the tick alignment. Thanks.

I'm out of time on this issue for the day, but I can give the axis ranges:
x: -6 to 6
y: 3.096916-0.125 to 3.096916+0.125

**Comment by szaydel** [comment]
@decibelcooper: Does using literal values or int() in your changeset possibly create issues with perhaps very large or very small numbers, or large ranges?

**Comment by decibelcooper** [comment]
@szaydel Not as far as I can tell.  The majority of the added code is identical to https://github.com/gonum/plot/blob/50336e281717e5f1685e3c611828dfb42c82cf66/axis.go#L347-L417

**Comment by szaydel** [comment]
@decibelcooper: Great, I probably should have had a closer look before asking. Literals always raise a flag for me when they are in the context of potentially unknown ranges of values, so I asked.
