### ISSUE TITLE
Example plot in Wiki out of date

### ISSUE THREAD

**Issue by ShaneSaww** [gonum/plot#409]
Not a big deal, but it caused me some minor pain with dep vendoring wiht the path of `github.com/gonum/plot`.

The example in the Wiki appears to be out of date and still using the imports of `"github.com/gonum/plot` instead of updated `gonum.org/v1/plot`.

**Comment by ShaneSaww** [comment]
Looks like anyone can update the Wiki so I just updated this section:
https://github.com/gonum/plot/wiki/Example-plots

Thanks!

**Comment by sbinet** [comment]
thanks!
(but perhaps we shouldn't leave everybody touch this :P. especially because, at least I, didn't get any notification about any modification...
