### ISSUE TITLE
vg: soften third-party dependencies 

### ISSUE THREAD

**Issue by fawick** [gonum/plot#412]
At the moment, installing `gonum.org/v1/plot/vg/draw` has a hard requirement on various non-vendored third-party packages. 

I'd like to propose a refactoring of the `vg/{draw,vgeps,vgimg,vgpdf,vgsvg}` so that implementations of `vg.Canvas` need to be registered, which the packages could do in their `func init()`.

This would make all third-party dependencies soft requirements and a user might choose not to fulfill some of them in case the respective output formats are not required (e.g. one might want to use PNG but have no need for PDF).

As a side benefit, this would make it easy to incubate new implementations of the `vg.Canvas` interface, as these no longer need to be hardwired to `vg/draw`.

(Incidentally, this would fix issues like #238, but that's not the objective here.)

**Comment by kortschak** [comment]
It would be good to see a plan for your implementation of this.

**Comment by fawick** [comment]
At the moment, I do not have plan, as I am not very familiar with the codebase. But if you are open to the general idea, I might get in deeper into the source and try to devise one in the next couple of weeks.

**Comment by kortschak** [comment]
I'm open to the idea, but it's worth waiting for input from others here. The issues that you may face is handling how `plot.WriterTo` and `plot.Save` work and are documented, but I don't see anything that would make handling those issues impossible.

**Comment by fawick** [comment]
As `plot.WriterTo` calls `draw.NewFormattedCanvas` which returns an error my naive approach would be to simply let that error be non-nil in case the requested format has not been registered, which would then trickle down the stack to `plot.Save` as well. I'd add to the documentation to `plot.Save` and `plot.WriterTo` that trying any non-registered format would lead to such an error.

I wonder whether this an API-breaking change, as on the one hand any using code would still compile while on the other hand the behaviour changes and care must be taken accordingly to import and register any implementations of the `plot.Canvas`interface. Does the fact that there are no release tags have an impact? I'd be genuinely interested in the thoughts of the gonum contributors on these questions.

**Comment by kortschak** [comment]
It will be breaking, but we aer breaking things at the moment. We had intended to freeze the API at the beginning of this year, but delays...

**Comment by fawick** [comment]
@kortschak So far, nobody else chimed in. Should we ping somebody specific to get input from?

**Comment by sbinet** [comment]
I am a bit of two minds here.
on the one hand, being able to slim down the amount of dependencies pulled down by `plot.Plot.Save` is nice and requiring people to `import _ "my/vg/backend"` definitely looks like a nice nod to `import _ "image/png"`.
on the other hand, this will break people's code at runtime...
but we could introduce something like `gonum.org/v1/plot/vg/vgall` that would register all the current backends.

**Comment by fawick** [comment]
As far as I understood from @kortschak breaking stuff is not showstopper here. I agree that it is very unfortunate that this would not already throw an error during compilation.

> but we could introduce something like gonum.org/v1/plot/vg/vgall that would register all the current backends.

Yes, that's what I had in mind, too. An additional mitigation of the break might be to have a `.go` with a `+build !minimal`  build constraint that will import `vg/vgall` for a certain deprecation period. In that case users that want to benefit from the softened dependency chain would need to define `-tags minimal` at build time for said deprecation period. (I'm not attached to the name `minimal` here).

What do you think?

**Comment by fawick** [comment]
I know you wanted to see a plan for this first, but when I was trying to come up with one I was really surprised how little code was needed to get this done. Hence, I present my plan in the form of a commit: https://github.com/fawick/plot/commit/f98e3e58864b4aab2d36f01f0735d0683f2988fb

**Comment by fawick** [comment]
Come to think of it, the package `vgall` is not needed. The file `import.go` could be part of `gonum.org/v1/plot` itself: fawick/plot@9eb0a40

**Comment by kortschak** [comment]
Broadly I think that is OK, though there are a couple of correctness issues. The registry must be protected by a mutex (see how the font registry is protected) and the use of an appended slice and use of first match means that a re-registration of a format with a new implementation is not effective - a map would be simpler too.

The default use of importing all (doing this in a build tag-protected file in plot as you suggest) does retain runtime compatibility, so I think people should be OK with that.

If you want to put together a PR taking into account these points we can review it.

**Comment by kortschak** [comment]
Also, registering a nil func should do delete (formats, name).

**Comment by fawick** [comment]
Thanks for the feedback! I wasn't thinking of re-registration, my blueprint was [the image package from stdlib](https://golang.org/src/image/format.go#L16). I'll use a map as suggested and submit a PR tomorrow.
