### ISSUE TITLE
path and type mess up when using dep ensure

### ISSUE THREAD

**Issue by XiaoboYuan** [gonum/plot#422]
I am new to golang and gonum, I hope I did not make a mistake on this.

I am trying to run a very simple demo which draws a histogram with gonum.
Here is the initial code:

```go
package main

import (
	"gonum.org/v1/plot"
	"github.com/naturali/LogProcessing/pkg/log"
)
func main() {
	p, err := plot.New()
	if err != nil {
		log.Fatal(err)
	}
	log.Info(p)
}
```

When I run dep ensure -v -update with this following constraint in Gopkg.toml:
```
[[constraint]]
  name = "gonum.org/v1/plot"
  branch = "master"
```

the log says:
```
? attempt gonum.org/v1/plot with 1 pkgs; 7 versions to try
(10)      try gonum.org/v1/plot@master
(11)  ✗   gonum.org/v1/plot at master has problem subpkg(s):
(11)    	gonum.org/v1/plot is missing; required by (root).
```

When I run the dep command without any constraint, it will download both the colorbar-rounding branch of "gonum.org/v1/plot" and the master branch of "github.com/gonum/plot"

Now when I run my demo and the log says that there is type mismatch, here is part of the log:

```
vendor/github.com/gonum/plot/vg/draw/canvas.go:276: cannot use w (type "github.com/naturali/LogProcessing/vendor/gonum.org/v1/plot/vg".Length) as type "github.com/naturali/LogProcessing/vendor/github.com/gonum/plot/vg".Length in argument to vgeps.New
vendor/github.com/gonum/plot/vg/draw/canvas.go:276: cannot use h (type "github.com/naturali/LogProcessing/vendor/gonum.org/v1/plot/vg".Length) as type "github.com/naturali/LogProcessing/vendor/github.com/gonum/plot/vg".Length in argument to vgeps.New
vendor/github.com/gonum/plot/vg/draw/canvas.go:276: cannot use vgeps.New(w, h) (type *vgeps.Canvas) as type "github.com/naturali/LogProcessing/vendor/gonum.org/v1/plot/vg".CanvasWriterTo in assignment:
	*vgeps.Canvas does not implement "github.com/naturali/LogProcessing/vendor/gonum.org/v1/plot/vg".CanvasWriterTo (wrong type for DrawImage method)
		have DrawImage("github.com/naturali/LogProcessing/vendor/github.com/gonum/plot/vg".Rectangle, image.Image)
		want DrawImage("github.com/naturali/LogProcessing/vendor/gonum.org/v1/plot/vg".Rectangle, image.Image)
```

I dived into the source code and found that it imports "gonum.org/v1/plot/vg" in the file "github.com/gonum/plot/vg/draw/canvas.go" and imports "github.com/gonum/plot/vg" in the file "gonum.org/v1/plot/vg/draw/canvas.go"

I think there are two copies of the same code with different paths in my vendor folder and they mess the paths up.

The version of golang I use is go1.8.3.
Again, hope it is not my mistake.

**Comment by btracey** [comment]
Sorry, I haven't used dep. This seems like a dep bug though, and not one on our end?

**Comment by sbinet** [comment]
(I have slightly updated your post so it renders better)

**Comment by sbinet** [comment]
I suspect some bad interaction with `dep`.
we haven't yet tagged anything in `gonum/plot`.
maybe that's the reason?

maybe somebody from golang/dep can pitch in? @sdboyer?

could you try removing the `vendor/github.com/gonum` stuff ?

**Comment by sdboyer** [comment]
hi! i'm happy you summoned me, i feel like not enough people do that 😄 

i can't quite tell what's going on here, but i can point out a weird thing, to start:

```
? attempt gonum.org/v1/plot with 1 pkgs; 7 versions to try
(10)      try gonum.org/v1/plot@master
(11)  ✗   gonum.org/v1/plot at master has problem subpkg(s):
(11)    	gonum.org/v1/plot is missing; required by (root).
```

this is quite surprising - it's telling us that, while it did (apparently) successfully clone down the repository behind `gonum.org/v1/plot`, apparently dep thinks there's actually no code there. this may indeed be a bug in dep - i'm not sure how this even could've happened, and i can't replicate it with either dep v0.3.2 or tip. @XiaoboYuan, what version of dep are you using, and could you confirm that this problem still arises with newer versions?

as for this part:

> I dived into the source code and found that it imports "gonum.org/v1/plot/vg" in the file "github.com/gonum/plot/vg/draw/canvas.go" and imports "github.com/gonum/plot/vg" in the file "gonum.org/v1/plot/vg/draw/canvas.go"

this is truly bizarre 😲 dep disallows the possibility of using anything other than a single snapshot of an entire repository in any given computed depgraph, so i'm not sure what's going on here; the only way this should be possible is if gonum itself had inconsistent import statements, but i couldn't find any on `master` - i see no import of `github.com/gonum/plot/vg` in the latest `master` of `gonum.org/v1/plot/vg/draw/canvas.go`.

i guess maybe the operant question is, when you say, "i dived into the source code," which source code do you mean? something in `vendor/`? on your `GOPATH`? in github's web UI?

**Comment by XiaoboYuan** [comment]
@sdboyer 
FYI, I dived into the source code in my ```vendor/``` and found those import statements in ```gonum.org/v1/plot/vg/draw/canvas.go```. I think these import statements can be found in the ```colorbar-rounding``` branch hosted by gonum.org though I cannot find the source code on web.


The problem has been solved by updating dep to the latest version, but there is still something confusing me. 

I cannot tell the dep version since there does not seem to be a ```dep version``` command. I use git log and find my dep is in an old version.

```
commit 14e9281c443c59b6482df8973588dbe22ef08834
Merge: 4f8c074 3d113ea
Author: sam boyer <tech@samboyer.org>
Date:   Tue Jul 18 23:48:00 2017 -0400

    Merge pull request #846 from matjam/master
    
    FAQ: Added instructions on configuring git authentication.
```

Then I run "go get -u github.com/golang/dep/cmd/dep" and dep is updated to the latest version.
```
commit 3a59b68597c76c889b2ff2854b30bc29e902b555
Merge: b745572 fcdb2ed
Author: Sunny <me@darkowlzz.space>
Date:   Fri Dec 8 23:30:47 2017 +0530

    Merge pull request #1420 from JamieCrisman/1410-handle-errors
    
    status: handle errors when writing output
```

I rm ```vendor/``` and run "dep ensure -v -update", something weird happens.
dep download ```colorbar-rounding``` branch of ```gonum.org/v1/plot``` and ```errors``` branch of ```github.com/gonum/plot``` and surprisingly the initial code now runs correctly.

Then I tried the histogram example in this link 
```"https://github.com/gonum/plot/wiki/Example-plots"``` 
and changed the import statements to 
```
"gonum.org/v1/plot/vg"
"gonum.org/v1/plot/plotter"
"gonum.org/v1/plot"
```

I rm ```vendor/``` and run "dep ensure -v -update" again and this time dep correctly downloads master of ```gonum.org/v1/plot``` and everything seems correct.

I tried several times to rm ```vendor/``` and run ''dep ensure -v -update'' and dep runs well and stably.

Just take this process down for your information.
Thank you all for your help.

**Comment by sdboyer** [comment]
this is turning into more of questions about dep, and i don't want to overly hijack this queue. so, just quickly things:

> I cannot tell the dep version since there does not seem to be a `dep version` command. 

there is now. dep from July is...very, very old 😄 

> dep download colorbar-rounding branch of gonum.org/v1/plot and errors branch of github.com/gonum/plot and surprisingly the initial code now runs correctly.

dep isn't downloading these individually. it's already cloned the entire repository under `$GOPATH/pkg/dep/sources/`. what you're seeing in the `-v` trace output is dep proceeding through different versions to find one that satisfies constraints.

> I tried several times to rm vendor/ and run ''dep ensure -v -update'' and dep runs well and stably.

glad to hear it!
