### ISSUE TITLE
plotutil and plotter

### ISSUE THREAD

**Issue by GitHubFatherIsMe** [gonum/plot#423]
I'm new here.Something I don't understand clearly.
plot.plotutil.addLinePoints and plot.plotter.newLinePoints both can plot a line,so where is the difference between them?

**Comment by sbinet** [comment]
one is implemented in terms of the other.

- [plotutil.AddLinePoints](https://godoc.org/gonum.org/v1/plot/plotutil#AddLinePoints) is a convenience function that uses 
- [plotter.NewLinePoints](https://godoc.org/gonum.org/v1/plot/plotter#NewLinePoints)

`plotutil.AddLinePoints` adds new `plotter.Line` and `plotter.Points` (via `plotter.NewLinePoints`) to the given `plot.Plot`, and automatically customizes the colors and style of the lines and points.
`plotutil.AddLinePoints` can also automatically add a legend for each of the given `plotter.XYer`.

hope that clears things up :)

**Comment by sbinet** [comment]
(by the way, I think this kind of question would be better directed at `gonum-dev@googlegroups.com` rather than on the issue tracker.)

closing this one... feel free to reopen if you disagree :)

**Comment by GitHubFatherIsMe** [comment]
I'm so happy to get your answer!
I'm a Chinese student,Go rises rapidly but still niche in China.
I choose Go as my first pragramming language that I want to study hard.
My major in school is bioinformatics. The language people in this dield all use python.
I still like Go,but how can I make a balance between my interest and my major?
So lucky to meet the package Gonum you participate in! It slove my puzzle perplexing me for weeks!
I couldn't expect any back about my first proplemon github nearly .
To my surprise,the author of package rely to me!!!
Thank you sincerely!

**Comment by btracey** [comment]
We're happy to have discussion, but as mentioned above it should be done on the mailing group.
