### ISSUE TITLE
plotter: Image and ColorBar don't adapt to non-linear axes

### ISSUE THREAD

**Issue by ctessum** [gonum/plot#426]
### What are you trying to do?
I would like to plot an Image or Color bar on a plot with a non-linear axis.

### What did you do?

I will submit a pull request with a reproduce

### What did you expect to happen?

The image should be warped to account for the non-linear axis.

### What actually happened?

The image assume the axis was linear even when it wasn't

### What version of Go and Gonum are you using?

go 1.10, gonum master

### Does this issue reproduce with the current master?
yes

**Comment by kortschak** [comment]
Gonum version https://github.com/gonum/plot/commit/f7bfba81f928e323040f41da93145e7f295ba3bf (master is a moving target, also I should fix the template to it refers to plot).

I'm really torn here, maybe you could explain why you want to do this. I can see times where you would want to deform an image, and times where you would want the image to just be blatted onto the canvas and the correct location, but I don't see a good reason for deforming a heat map key this way.

**Comment by ctessum** [comment]
My immediate use case is for color bars. The log-scale color bar included in #427 is one example; another one is this:

![colorbarhorizontal](https://user-images.githubusercontent.com/6193153/36569885-6afca120-17e4-11e8-9ab4-1cc95e5507bc.png)

... which I use for data that is for the most part normally distributed with some outliers, where a linear scale with a break in it seems to work better than anything else I have thought of or seen. I think the color bar pasted above is probably too specific to actually include in the library, but the only way I can think to implement it is if the image gets warped to match the axis scale.

From a more general perspective, I think that since the corners of the image are tied to data coordinates (not canvas coordinates), the pixels of the image should also be. If a user just wants to "blat" an image onto the canvas, they would use `canvas.DrawImage`.

Looking forward, I think there are some asthetic [issues](https://github.com/gonum/plot/blob/master/palette/moreland/testdata/moreland_golden.png) with the current vector-based implementation of `plotter.HeatMap` (i.e., the white lines that show up between grid cells), which could be fixed with a raster-based implementation. HeatMaps are another case where we probably would want the image to warp to the axis scale.

The only use case I can think where a user would not want the image to be warped if they wanted to use image-based glyphs for their data point markers or something like that. But, as the size of glyphs are defined using canvas coordinates rather than data coordinates, that is probably another case where that would be better implemented with `canvas.DrawImage` rather than `plotter.Image`.

**Comment by kortschak** [comment]
The example at [#427](https://github.com/gonum/plot/blob/3ab221a4fe25b8ff5fc356ab499351c07f97e3fe/plotter/testdata/colorBarHorizontalLog_golden.png) is odd; it looks to me like you lose all the benefit of placing values on the log scale since the left hand end of the colour scale is essentially black.

Can we not do this in a more composable way by making it possible to generate log (or other f()) scaled images, maybe a function that takes a `*plotter.Image` and returns a new one that has been scaled according to a provided `func(float64) float64`?

**Comment by ctessum** [comment]
It is true that the log scale color bar in #427 is not immediately useful. To be useful it would have to be combined with a ColorMap that was also log-transformed. At least with this PR, however, the values in the color bar correctly represent the values in the ColorMap.

It is definitely possible to make the warping optional on either an opt-in or an opt-out basis, either using a composable function or a boolean flag somewhere. However, I still can't think of any use cases where a user *wouldn't* want the image to be transformed.

**Comment by ctessum** [comment]
Ping?

**Comment by kortschak** [comment]
Can you change the colour map you are using in the PR to a grey scale (or even the one above)? That would make the benefit clearer. Also adding a scatter data set (or whatever you are using in the real world case - simplified if necessary) would make this more convincing.

**Comment by ctessum** [comment]
Sure. Here is a real-world example using population density in the United States:

![pop_density](https://user-images.githubusercontent.com/6193153/36761595-a989d8ba-1bd4-11e8-8185-7e10aaf08a8d.png)

It's not a perfect example for this case but it's what I have lying around. You can see that there's a distribution of densities in the 0-10,000, and then there's the top one percentile of locations (it looks like exclusively in New York City) with densities of 10,000 - 60,000. The color scale has a discontinuity at the 99th percentile, which is approximately 10,000. There are several reasons not to map population density with a log scale, one of which is there are a lot of zero values.

However, in my mind discontinuous color maps are tangential to the main issue at hand, which is whether image *data* should be mapped to the axes scales, or just the image *corners*. I still can't think of any cases where the latter would be preferable.

**Comment by kortschak** [comment]
Yeah, fair enough. Please make the test case a grey scale though.
