### ISSUE TITLE
vg: drop use of github.com/jteeuwen/go-bindata

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#432]
This has made the news lately but I forgot we were using that package in gonum/plot.

we should replace it with something else.

**Comment by kortschak** [comment]
Can you provide background please. I had not heard anything about this.

**Comment by sbinet** [comment]
Sure: https://twitter.com/francesc/status/961249107020001280?lang=en

**Comment by kortschak** [comment]
Wow! That's not good.

**Comment by kortschak** [comment]
https://github.com/rakyll/statik?

**Comment by sbinet** [comment]
I have also come across:
https://github.com/gobuffalo/packr

(I have been using it for my Go based forum. it's serviceable.)

**Comment by sbinet** [comment]
something to look for :`//go:embed`

https://go.googlesource.com/proposal/+/master/design/draft-embed.md

**Comment by sbinet** [comment]
this has been done at some point.
