### ISSUE TITLE
missing Mercurial command when installing plot

### ISSUE THREAD

**Issue by sgon00** [gonum/plot#438]
When I install plot by following the README, I got this error and failed to install:

```
$ go get gonum.org/v1/plot/...
go: missing Mercurial command. See https://golang.org/s/gogetcmd
package bitbucket.org/zombiezen/gopdf/pdf: exec: "hg": executable file not found in $PATH
```

Is this expected? Is Mercurial a prerequisite? I don't find this requirement in the readme. Why do I need a source control system when I install a plot tool? and this plot tool is actually managed by git scm instead of Mercurial. 

Thanks a lot.

**Comment by sbinet** [comment]
`gonum/plot` is indeed hosted on GitHub, but one of its dependencies (`bitbucket.org/zombiezen/gopdf`) isn't.

that said, it probably won't be the case for too long:
- https://github.com/gonum/plot/pull/433
- https://github.com/gonum/plot/issues/389
