### ISSUE TITLE
Multilingual (custom ttf) font support in vg.MakeFont ?

### ISSUE THREAD

**Issue by sgon00** [gonum/plot#440]
Hi, I am a newbie and read some Multilingual issues, but I don't really understand them. I am trying to use this code https://gist.github.com/linw1995/41e103f29e7dd97679c577a6f4830be8 to create watermark on images. It works fine when I use only English characters and failed to show the text when I use Asian fonts in command line argument. 

I tried to provide CJK fonts name in the code, for example `fontStyle, _ := vg.MakeFont("Noto Sans CJK SC", vg.Inch*0.7)`, but it failed to run and report nil pointer error. 

Is this doable now? I am sorry if this is a duplicated issue since I am new to this and don't really understand other issues discussion. 

Thank you very much for your help.

**Comment by sbinet** [comment]
a couple or remarks:

- don't use imports from `github.com/gonum/plot/...` they are deprecated, prefer: `gonum.org/v1/plot`
- check your errors (`MakeFont` should return a non-nil error)

`gonum/plot` ships with a very narrow set of fonts by default.
if you want to use one with support for non-Latin characters, you'll have to first register that font with the `plot/vg` package.

here is an example:
https://gist.github.com/sbinet/ee0f0918e7050d6060b3b6eb744a24bb

**Comment by sgon00** [comment]
@sbinet Thank you very much for your quick reply and detail explanation with a working example code. It works very well and I tried to load my local ttf with the following code too:

```
ttfBytes, err := ioutil.ReadFile("/path/local.ttf")
font, err := truetype.Parse(ttfBytes)
vg.AddFont(*fontName, font)
```

It works great. 
Thank you very much again!
