### ISSUE TITLE
vg: add example for loading/using non-Latin fonts

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#441]
we should probably add an example for loading and then using a non pre-registered font (possibly a non-english/non-latin one) to the `vg` package.

- example with `png`
- example with `pdf`
- example with `svg`

an example with `tex` might be complicated...

**Comment by aphecetche** [comment]
@sbinet don't know if this is what you are talking about here, but I'd be very interested to get an example of how to get the label of a plot axis showing some greek characters...

**Comment by sbinet** [comment]
nope, that wasn't it :)
what I think you are hinting at is `$\eta$`, right?
for that kind of plot, one usually rely on the `vgtex` backend.

otherwise, one can also use UTF-8 characters, such as: η or Ψ.

```go
package main

import (
	"log"
	"math"

	"gonum.org/v1/plot"
	"gonum.org/v1/plot/plotter"
	"gonum.org/v1/plot/vg"
)

func main() {
	pl, err := plot.New()
	if err != nil {
		log.Fatal(err)
	}

	pl.Title.Text = "J/Ψ stuff"
	pl.X.Label.Text = "η"
	pl.X.Min = -math.Pi
	pl.X.Max = +math.Pi
	pl.Y.Label.Text = "Stuff (A.U)"

	pl.Add(plotter.NewGrid())
	err = pl.Save(20*vg.Centimeter, 10*vg.Centimeter, "out.png")
	if err != nil {
		log.Fatal(err)
	}
}
```
![out](https://user-images.githubusercontent.com/1070920/48855438-57ef5900-edb4-11e8-9743-342dc161c16e.png)

**Comment by sbinet** [comment]
this was actually fixed w/ https://github.com/gonum/plot/pull/567.

@aphecetche you may want to have a look at what @rmadar did with his `TTree` go-analyzer:
- https://github.com/rmadar/tree-gonalyzer
![img](https://github.com/rmadar/tree-gonalyzer/raw/master/ana-show/eg-plot.png)
![truth_dphi_ll](https://user-images.githubusercontent.com/1070920/82735850-1763f900-9d25-11ea-8693-6a0e712ded3e.png)

(also the recent nice perf improvements of `groot`, beating ROOT/C++)

**Comment by sbinet** [comment]
ah, and for general math expression rendering (w/ all backends), there's a WIP PR: https://github.com/gonum/plot/pull/616

which will allow, at some point, to leverage this:
- https://github.com/go-latex/latex
- https://github.com/go-latex/latex/tree/master/mtex
![mtex-example](https://github.com/go-latex/latex/raw/master/mtex/testdata/mtex-example.png)
