### ISSUE TITLE
vg/vgpdf: pdfs don't render circle glyphs properly

### ISSUE THREAD

**Issue by btracey** [gonum/plot#451]
Example code:

```
package main

import (
	"gonum.org/v1/plot"
	"gonum.org/v1/plot/plotter"
	"gonum.org/v1/plot/vg"
)

func main() {
	pts := plotter.XYs{{1, 1}, {2, 2}, {3, 3}, {1.5, 2}, {2.5, 1}}
	scat, err := plotter.NewScatter(pts)
	if err != nil {
		panic(err)
	}
	p, err := plot.New()
	if err != nil {
		panic(err)
	}
	p.Add(scat)
	p.Save(5*vg.Inch, 3*vg.Inch, "plt.pdf")
	p.Save(5*vg.Inch, 3*vg.Inch, "plt.png")
}
```

The png file looks normal

![plt](https://user-images.githubusercontent.com/3680859/40809683-8ce3792a-64e8-11e8-9d00-6cc2dbfad5de.png)

The pdf, however, renders the circles with dashed lines instead of solid ones.
[plt.pdf](https://github.com/gonum/plot/files/2060168/plt.pdf)

I suspect this is related to using `gofpdf`, because this problem surfaced when I pulled to the current master. 

cc @sbinet

**Comment by kortschak** [comment]
They look like they are slightly rotated. At a guess, it's an issue with `vgpdf.Canvas.arc`; this is made more likely by the observation that the quarter segments in the example are clearly not quarter circles.
