### ISSUE TITLE
Infinite loop drawing histogram

### ISSUE THREAD

**Issue by rosshemsley** [gonum/plot#459]
The following code seems to loop infinitely on `p.Save`:

```go
p, err := plot.New()
if err != nil {
	panic(err)
}

hist, err := plotter.NewHist(plotter.Values([]float64{1.0}), 60)
hist.Normalize(1)

p.Add(hist)
err = p.Save(4*vg.Inch, 4*vg.Inch, "hist.png")
if err != nil {
	panic(err)
}
```

The problem is in the function below:
```go
// Normalize normalizes the histogram so that the
// total area beneath it sums to a given value.
func (h *Histogram) Normalize(sum float64) {
	mass := 0.0
	for _, b := range h.Bins {
		mass += b.Weight
	}
	for i := range h.Bins {
		h.Bins[i].Weight *= sum / (h.Width * mass)
	}
}
```

Since `h.Width` is zero, an infinity appears that breaks the render to the canvas

It's not totally obvious what should be done here, perhaps set the bin width to 1.0 for trivial histograms?

**Comment by kortschak** [comment]
While users probably shouldn't be making histograms with single bins, we also shouldn't be hanging on them for doing so. Under this basis, I'm happy to give back an imperfect plot and not hang.

**Comment by btracey** [comment]
Shouldn't we just give a width of 1 for the case that they are all the same value? It happens, especially with programmatically generated data that you make a histogram with all the same value. Seeing a histogram with exactly 1 bar is a sign that you've done something wrong.

**Comment by kortschak** [comment]
>Shouldn't we just give a width of 1 for the case that they are all the same value?

That's what the PR does.

**Comment by btracey** [comment]
Got it. I'm sorry.

**Comment by sbinet** [comment]
FYI, that's one of the many reasons why in particle physics everybody uses proper types (with methods) to create and fill histograms (and handle under/over-flows, regular binning, variable binning, etc...)

see, for example:
- https://godoc.org/go-hep.org/x/hep/hbook#H1D
- https://godoc.org/go-hep.org/x/hep/hplot#H1D
