### ISSUE TITLE
internal/cmpimg: export as gonum.org/v1/plot/cmpimg

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#464]
Comparing plot outputs (PNG, PDF, JPG, ...) for tests is useful not only in `gonum/plot` but also for clients using `gonum/plot`, outside of this repository.

we should consider exporting `gonum.org/v1/plot/internal/cmpimg`.
perhaps simply as `gonum.org/v1/plot/cmpimg` ?

**Comment by ctessum** [comment]
I would be in favor of something like that.
