### ISSUE TITLE
Set/force vertical axis min and max

### ISSUE THREAD

**Issue by hlalibe** [gonum/plot#467]
I need to output various charts (line and bars) to different images so they can then be compared afterwards. The important thing for this is that the vertical axis minimum and maximum values are always the same regardless of the data plotted on each chart. So for example vertical axis is always between -100 and 100 regardless if data spans much less than these limits or more.

Is there a way to do this ? I don't see it in the docs.

I've read about something similar, link below, but it seems to be about aligning different subplots. I can't use subplots for this, they need to be on separate images, I've got thousands of them:
https://github.com/gonum/plot/pull/354

**Comment by sbinet** [comment]
you should be able to do that like so:
```go
p, err := plot.New()
if err != nil {
    panic(err)
}
p.Y.Min = -42
p.Y.Max = +42
```

see:
- https://godoc.org/gonum.org/v1/plot#Plot
- https://godoc.org/gonum.org/v1/plot#Axis

**Comment by hlalibe** [comment]
Thanks Sebastien,

I've tested it, works fine, just one question/remark:
Is it correct that the actual data min and/or max can override my own min/max if the data itself is outside my min/max range ?
At least that's what i'm seeing after a few tests. So for example if my data is only between 8'000 and 10'000, then I set my min and max at 2'000 and 3'000, i would expect to see a blank chart, but i don't, instead i see my data smashed on the top part of the chart with blank below, as if the max is now the max of my data (10'000 instead of 3'000) and the min comes from the one i set at 2'000.

It's better than nothing, but my goal was also to eliminate the extreme outliers so they don't impact my vertical scale. Now it seems they will if i don't remove them first from my data, which is not that practical to do, although I guess it would not be that complicated to code, but it might slow down my program, I've got thousands of these charts to produce and i'll need to do that often.

See what I mean ?

**Comment by kortschak** [comment]
Can you post an image of what you are seeing and the code that generates it please. From looking at the various plotters we provide this looks like it is coming from the lines rather than the bars (`BarChart` clearly does do data point clipping, `Line` and `Scatter` do not and should). Can you confirm that `BarChart` works as expected, but `Line` does not?

**Comment by hlalibe** [comment]
Hey Dan,
So below is a bar chart with min/max set at -50/+50, which is wider than the data max/min, all good.
 ![image](https://user-images.githubusercontent.com/36799424/44002737-108e502c-9e48-11e8-9473-af46c306aaa9.png)

Then the same code but with min/max at -10/+10, which is narrower than the data min/max. Here we see that the data min/max overrides my min/max.
![image](https://user-images.githubusercontent.com/36799424/44002749-31c56a82-9e48-11e8-9e5c-ead2d2f27c6e.png)
I'll make a separate post for the line chart, here's my code for these bar charts:

```
package main

import (
	"gonum.org/v1/plot"
	"gonum.org/v1/plot/plotter"
	"gonum.org/v1/plot/plotutil"
	"gonum.org/v1/plot/vg"
)

func main() {

	groupA := plotter.Values{20, 35, 30, 35, 27}
	groupB := plotter.Values{-25, -32, -34, -20, -25}

	p, err := plot.New()
	if err != nil {
		panic(err)
	}
	p.Title.Text = "Bar chart with Min/max -50/+50"
	p.Y.Label.Text = "Heights"
	w := vg.Points(20)
	p.Y.Min = -10
	p.Y.Max = 10

	//*********************************************************

	barsA, err := plotter.NewBarChart(groupA, w)
	if err != nil {
		panic(err)
	}
	barsA.LineStyle.Width = vg.Length(0)
	barsA.Color = plotutil.Color(0)
	barsA.Offset = 0

	//*********************************************************	

	barsB, err := plotter.NewBarChart(groupB, w)
	if err != nil {
		panic(err)
	}
	barsB.LineStyle.Width = vg.Length(0)
	barsB.Color = plotutil.Color(1)
	barsB.Offset = 0

	p.Add(barsA, barsB)

	if err := p.Save(5*vg.Inch, 3*vg.Inch, "/media/hugues/M.2 windows/Hugues/Snaps/barchart.png"); err != nil {
		panic(err)
	}
}
```

**Comment by hlalibe** [comment]
Following from my previous post, now with a line chart, Y data ranges from 10 to 100. Behavior seems to be the same as per bar chart example above.
So below is a line chart with min/max set at -50/+150, which is wider than the data max/min, all good.
![image](https://user-images.githubusercontent.com/36799424/44003179-ece75086-9e4e-11e8-881b-c172d06a04e0.png)

Then the same code but with min/max at +30/+50, which is narrower than the data min/max. Here we see that the data min/max overrides my min/max.
![image](https://user-images.githubusercontent.com/36799424/44003189-09939140-9e4f-11e8-80ae-8afc5f66d21c.png)

And my code:

```
package main

import (
	"gonum.org/v1/plot"
	"gonum.org/v1/plot/plotter"
	"gonum.org/v1/plot/vg"
)

func main() {


		ptsXY := make(plotter.XYs, 10)
		for m := range ptsXY {
			ptsXY[m].X = float64(m+1)
			ptsXY[m].Y = float64((m+1) * 10)
			m = m + 1	
		}

		//create chart  *************************************************
		p2, err := plot.New()
		if err != nil {
			panic(err)
		}
		p2.Title.Text = "Line chart with Min/max -50/+150"
		p2.Y.Min = 30
		p2.Y.Max = 50

		line_book_trade, err := plotter.NewLine(ptsXY)
		if err != nil {
			panic(err)
		}

		p2.Add(line_book_trade)


	if err := p2.Save(5*vg.Inch, 3*vg.Inch, "/media/hugues/M.2 windows/Hugues/Snaps/linechart.png"); err != nil {
		panic(err)
	}


}
```

**Comment by kortschak** [comment]
OK, I can take a look at that. Can you tell me what you expect for the `BarChart` case? There are two options, omitting the bar that extends beyond the range, or truncating the bar at the range ends.

**Comment by kortschak** [comment]
Note that the setting of `Min` and `Max` should happen after the call to `Add`. We should probably document this better.

**Comment by kortschak** [comment]
I have confirmed that both of these work correctly if the range is set after the call to `Add`. Looking at the documentation for `Add` it says:
```
// If the plotters implements DataRanger then the
// minimum and maximum values of the X and Y
// axes are changed if necessary to fit the range of
// the data.
```

This indicates that the range should be set after a call to `Add` since the call ensures the range includes all the data. I don't see how this can be made clearer.
