### ISSUE TITLE
vg: missing quadratic and cubic path elements

### ISSUE THREAD

**Issue by ktye** [gonum/plot#482]
Is there a way to use quadratic and cubic bezier elements in vg?
From looking at the source, it seems that vg.Path does not provide these primitives.
As they are elementary to 2d vector graphics, I think they should be present.

I propose to add the constant:
```go
const (
	MoveComp = iota
	LineComp
	ArcComp
	CurveComp // This is new
	CloseComp
)
```

And the methods
```go
// QuadTo adds a quadratic curve element to the path defined by the control point p1 and the endpoint pt.
func (p *Path) QuadTo(p1, pt Point){...}

// CubeTo adds a cubic curve element to the path defined by the control points p1 and p2 and the endpoint pt.
func (p *Path) CubeTo(p1, p2, pt Point){...}
```

All backends should be able to handle the primitives:

- eps: curveto which is like CubeTo. QuadTo can be implemented by setting p1=p2
  - https://www.math.ubc.ca/~cass/graphics/manual/pdf/ch6.pdf (page 2, sec 6.2)
- img: draw2d has QuadCurveTo and CubicCurveTo
- pdf: gopdf has CurveTo and CurveBezierCubicTo
- svg: svgo has Qbez and Bezier
- tex: pgf has control points, which I hope are compatible
  - http://www.math.uni-leipzig.de/~hellmund/LaTeX/pgf-tut.pdf (page 8)

Did I miss anything?

What do you think?

**Comment by sbinet** [comment]
This has bugged me as well. (Or at least, made me quizzical)

I'd be voting for adding this new path element.

**Comment by kortschak** [comment]
You can get bezier segments and draw them. We have https://godoc.org/gonum.org/v1/plot/tools/bezier.

**Comment by ktye** [comment]
I have seen that, but I think this is different:
bezier.Curve(p []vg.Point) returns an approximation with linear segments, where as my proposal is to add the primitives.
Of course, for a workaround this can be used (resulting in a bigger output files for all formats).
My question is, if we should add the primitives or not.

**Comment by kortschak** [comment]
At some point, all beziers are approximations with linear segments.

Also, don't plan on things based on draw2d. We should not be using it.

**Comment by sbinet** [comment]
`fogleman/gg` has the needed bits too:

- https://godoc.org/github.com/fogleman/gg#Context.CubicTo
- https://godoc.org/github.com/fogleman/gg#Context.QuadraticTo

**Comment by ktye** [comment]
Whatever the decision is, I have implemented a demonstration.
I think the primitives match quite well into the vg packet. The implementation for all backends was straight-forward.

There should not be a risk, if the backend for images is changed. Most rasterizers have the functions, e.g. golang.org/x/image/vector.

See the changes at ktye/plot@f7e5651

```go
// The program demonstrates quadratic and cubic path primitives for plot/vg.
// Call the program with the output format and redirect the output to make the test image.
//
// 	go run main.go "eps" > out.eps
// 	go run main.go "png" > out.png
// 	go run main.go "pdf" > out.pdf
// 	go run main.go "svg" > out.svg
// 	go run main.go "tex" > out.tex
package main

import (
	"image/color"
	"os"

	"gonum.org/v1/plot/vg"
	"gonum.org/v1/plot/vg/draw"
	"gonum.org/v1/plot/vg/vgtex"
)

func main() {

	if len(os.Args) != 2 {
		panic("arg[1]: must be format, e.g. png, svg, ...")
	}

	format := os.Args[1]
	width, height := vg.Length(100), vg.Length(100)

	var cw vg.CanvasWriterTo
	if format == "tex" {
		// "tex" does not exist in NewFormattedCanvas.
		cw = vgtex.NewDocument(width, height)
	} else {
		var err error
		cw, err = draw.NewFormattedCanvas(width, height, format)
		if err != nil {
			panic(err)
		}
	}
	defer cw.WriteTo(os.Stdout)

	p0 := vg.Point{}
	p1 := vg.Point{20, 80}
	p2 := vg.Point{100, 100}
	p3 := vg.Point{50, 100}
	pt := vg.Point{80, 20}

	// Black polygon.
	var p vg.Path
	p.Move(p0)
	p.Line(p1)
	p.Line(p2)
	p.Line(pt)
	cw.Stroke(p)

	// Red quadratic curve.
	p = nil
	p.Move(p0)
	p.QuadTo(p3, pt)
	cw.SetColor(color.RGBA{255, 0, 0, 255})
	cw.Stroke(p)

	// Green cubic curve.
	p = nil
	p.Move(p0)
	p.CubeTo(p1, p2, pt)
	cw.SetColor(color.RGBA{0, 255, 0, 255})
	cw.Stroke(p)

	// Blue cubic curve with p1 p2 swapped.
	p = nil
	p.Move(p0)
	p.CubeTo(p2, p1, pt)
	cw.SetColor(color.RGBA{0, 0, 255, 255})
	cw.Stroke(p)

}
```

**Comment by kortschak** [comment]
@eaburns Do you have a view on this?

**Comment by eaburns** [comment]
Sorry for the slow response. I didn't add these originally because honestly I didn't need Bezier curves for anything I was plotting. If I recall correctly, I only needed circular arcs so that I could draw circle scatter plot glyphs. I don't see any reason not to include these if all backends support it. And, @kortschak points out (though I think his intention was to argue against adding these), if a backend doesn't support it then that backend can approximate it with line segments.

**Comment by kortschak** [comment]
OK. I'm happy with that. Thanks.

**Comment by ktye** [comment]
Is that a general agreement?
What to do next, should I send a PR, or should we discuss the details and variable names?
I used CubeTo and QuadTo for the methods, I think thats fine.
Not so sure about the PathComp field. I used `Control []Point` to store one or two control points.

**Comment by sbinet** [comment]
@ktye I guess everybody is on-board with moving this forward.
I suppose we could start with a PR. do you want to give it a try?
