### ISSUE TITLE
install 'go get gonum.org/v1/plot/... ' timeout

### ISSUE THREAD

**Issue by Elvins** [gonum/plot#490]
cmd: go get -v gonum.org/v1/plot/...

Fetching https://gonum.org/v1/plot?go-get=1
https fetch failed: Get https://gonum.org/v1/plot?go-get=1: dial tcp 178.128.123.58:443: i/o timeout
package gonum.org/v1/plot/...: unrecognized import path "gonum.org/v1/plot/..." (https fetch: Get https://gonum.org/v1/plot?go-get=1: dial tcp 178.128.123.58:443: i/o timeout)

how can I get this package?

**Comment by sbinet** [comment]
are you behind a firewall?
I just tried (from a french IP) and it worked...

**Comment by Elvins** [comment]
> are you behind a firewall?
> I just tried (from a french IP) and it worked...

It didn't work from a Chinese IP and I also can't the "https://gonum.org/v1/plot?go-get=1" in the browser. It show "Page not found Maybe you were looking for one of these?"
So sad.

**Comment by sbinet** [comment]
to follow up on what @btracey said:
```sh
$> cd $GOPATH/src
$> git clone git@github.com:gonum/plot gonum.org/v1/plot
$> go get gonum.org/v1/plot/...
```

**Comment by sbinet** [comment]
also: can you `ping gonum.org` ?
```
$> ping gonum.org
PING gonum.org (167.99.129.42) 56(84) bytes of data.
64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=1 ttl=55 time=23.4 ms
64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=2 ttl=55 time=17.2 ms
64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=3 ttl=55 time=18.4 ms
64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=4 ttl=55 time=19.1 ms
64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=5 ttl=55 time=19.6 ms
^C
--- gonum.org ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 627ms
rtt min/avg/max/mdev = 17.186/19.528/23.357/2.076 ms

```

**Comment by Elvins** [comment]
> also: can you `ping gonum.org` ?
> 
> ```
> $> ping gonum.org
> PING gonum.org (167.99.129.42) 56(84) bytes of data.
> 64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=1 ttl=55 time=23.4 ms
> 64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=2 ttl=55 time=17.2 ms
> 64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=3 ttl=55 time=18.4 ms
> 64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=4 ttl=55 time=19.1 ms
> 64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=5 ttl=55 time=19.6 ms
> ^C
> --- gonum.org ping statistics ---
> 5 packets transmitted, 5 received, 0% packet loss, time 627ms
> rtt min/avg/max/mdev = 17.186/19.528/23.357/2.076 ms
> ```

I can ping gonum.org
PING gonum.org (178.128.115.5): 56 data bytes
64 bytes from 178.128.115.5: icmp_seq=0 ttl=50 time=42.123 ms
64 bytes from 178.128.115.5: icmp_seq=1 ttl=50 time=43.950 ms
64 bytes from 178.128.115.5: icmp_seq=2 ttl=50 time=44.333 ms

**Comment by sbinet** [comment]
ok... reaching my level of incompetence, there.

but did the `git clone` workaround fit the bill?

**Comment by Elvins** [comment]
> ok... reaching my level of incompetence, there.
> 
> but did the `git clone` workaround fit the bill?

I try below cmd:
$> cd $GOPATH/src
$> git clone git@github.com:gonum/plot gonum.org/v1/plot
$> go get gonum.org/v1/plot/...

but when running the third cmd, it show that:
sudo go get gonum.org/v1/plot/...
package gonum.org/v1/plot/...: unrecognized import path "gonum.org/v1/plot/..." (https fetch: Get https://gonum.org/v1/plot?go-get=1: dial tcp 206.189.89.118:443: i/o timeout)

**Comment by sbinet** [comment]
you shouldn't need to run `go get` as `root`.

please drop `sudo`.

**Comment by Elvins** [comment]
> you shouldn't need to run `go get` as `root`.
> 
> please drop `sudo`.

My GOPATH is the root path. If I drop `sudo`, it can't run mkdir.

**Comment by Elvins** [comment]
> you shouldn't need to run `go get` as `root`.
> 
> please drop `sudo`.

thx, it run.
but there are still some problems...
package golang.org/x/image/math/fixed: unrecognized import path "golang.org/x/image/math/fixed" (https fetch: Get https://golang.org/x/image/math/fixed?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/image/font: unrecognized import path "golang.org/x/image/font" (https fetch: Get https://golang.org/x/image/font?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by sbinet** [comment]
Hum, it seems none of the vanity import paths (gonum.org, golang.org) work for your box.

That's pretty weird.

What version of Go are you using?
('go version', also, 'go env' would be good too)

**Comment by PengQIU2** [comment]
you can configure your Go environment to use a Chinese server by doing:
`go env -w GOPROXY=https://goproxy.cn`
