### ISSUE TITLE
p.X.Label.Text

### ISSUE THREAD

**Issue by listr0ng** [gonum/plot#499]
p.X.Label.Text  This variable does not support Chinese

**Comment by sbinet** [comment]
Thanks for the report, but, could you be a bit more explicit?
What did you try? (With some code :))
What did you expect?
What did you get instead?

**Comment by sbinet** [comment]
ping @listr0ng

**Comment by jindongyi011039** [comment]
hi, @sbinet , this is the sample code and image。

func main() {
	rand.Seed(int64(0))
	plot.DefaultFont = "Helvetica"
	p, err := plot.New()
	if err != nil {
		panic(err)
	}

	p.Title.Text = "Plotutil 中文"

	err = plotutil.AddLinePoints(p,
		"First", randomPoints(15),
		"Second", randomPoints(15),
		"Third", randomPoints(15))
	if err != nil {
		panic(err)
	}

	// Save the plot to a PNG file.
	if err := p.Save(8*vg.Inch, 4*vg.Inch, "points.png"); err != nil {
		panic(err)
	}
}
![image](https://user-images.githubusercontent.com/18360033/68283993-93fbf680-00b7-11ea-8042-76f7c09fb024.png)

**Comment by sbinet** [comment]
ok. well, IIRC, the default font doesn't support Chinese.

here is an example that shows how to load a font that does:
https://github.com/gonum/plot/issues/208#issuecomment-297102483

**Comment by sbinet** [comment]
I've added a simple example in #567.

here is what it gives:
![mincho-font](https://user-images.githubusercontent.com/1070920/68304577-5478de80-00a6-11ea-890e-2fde6ef99b2d.png)

**Comment by jindongyi011039** [comment]
yes ， if you want display japanese or chinese, first ,you must load truetype fonts, this is some sample code.
`func main() {
	rand.Seed(int64(0))

	var fontfile = flag.String("fontfile", "./msyh.ttc", "filename of the yahei font")
	flag.Parse()

	// Read the font data.
	fontBytes, err := ioutil.ReadFile(*fontfile)
	if err != nil {
		panic(err)
		return
	}
	f, err := freetype.ParseFont(fontBytes)
	if err != nil {
		panic(err)
		return
	}
	vg.AddFont("msyh", f)
	plot.DefaultFont = "msyh"
	p, err := plot.New()
	if err != nil {
		panic(err)
	}

	p.Title.Text = "Plotutil 中文"

	err = plotutil.AddLinePoints(p,
		"First", randomPoints(15),
		"Second", randomPoints(15),
		"Third", randomPoints(15))
	if err != nil {
		panic(err)
	}

	// Save the plot to a PNG file.
	if err := p.Save(8*vg.Inch, 4*vg.Inch, "points.png"); err != nil {
		panic(err)
	}
}`

then, you will display correct language.
![image](https://user-images.githubusercontent.com/18360033/68349592-a8cc9e80-0138-11ea-8474-94b0261c7b64.png)

**Comment by sbinet** [comment]
it's now an example of `gonum.org/v1/plot/vg`:
https://godoc.org/gonum.org/v1/plot/vg#example-package--AddFont

![img](https://user-images.githubusercontent.com/1070920/68304577-5478de80-00a6-11ea-890e-2fde6ef99b2d.png)
