### ISSUE TITLE
vgsvg enhancement: use <style> to reduce svg code size

### ISSUE THREAD

**Issue by chmike** [gonum/plot#519]
### What are you trying to do?
Make the svg code more compact. 

### What you suggest to do ?
Define styles in style blocks to avoid describing the full style repeatedly in each tag.  Use [style definition](https://developer.mozilla.org/fr/docs/Web/SVG/Element/style) in the svg code.

**Comment by chmike** [comment]
Code ready, but there is one caveat. 

Styles defined inside `<style>` have a file wide scope. If multiple svg are copied inside the same html file, we would have class name collisions.

The recommended solution is to add a unique ID (e.g. randomly picked) to the svg tag and prepend class selector in the style with this tag id. 

I would like to know what I should do about it. I can use a predefined id (e.g. svgID) that the user may  then replace with another one when needed. This replacement can be automated without too much trouble: `id="svgID"` -> `id="newID"` and ` #svgID .st` -> ` #newID .st`

Another solution could be to generate a random id, but this makes testing by comparison with a golden svg no possible anymore. 

What should I do ?

**Comment by chmike** [comment]
Opted for a predefined svg id "svgID" to ease testing by comparison. 

The absence of class name conflicts when two plots with different style are displayed by the same html file remains to be tested.

**Comment by chmike** [comment]
I discovered three regressions with this change. 

The first regression is that the image viewer of Gnome can’t display images with CSS styles. It can display images without this optimization. 

The second regression is that we can’t view, edit or annotate the plots with InkScape (a vector image editor). I don’t know the status with Adobe Illustrator. 

A third regression is that the svg with styles can’t be processed by imgur. I guess they use the same lib to render svg as eye of Gnome, the image viewer of Gnome.

In my opinion, these are sufficient to justify a canceling of the PR.

**Comment by kortschak** [comment]
Please file an issue and we can send a PR to revert this.
