### ISSUE TITLE
vg/draw: add Grid

### ISSUE THREAD

**Issue by josharian** [gonum/plot#521]
It'd be nice to (someday) add subplot support. This proposal takes one step toward that and makes it easier in the meantime for folks to implement subplots themselves.

I propose that we add vg/draw.Grid:

```go
// Grid divides canvas into a (cols, rows) grid of canvases.
// minpad is the minimum padding applied around the edges and between each grid element.
// Grid may increase minpad, usually by a small amount,
// to ensure that all canvases in the grid have integral bounding boxes,
// to improve the visual quality of anything rendered to them.
func Grid(canvas Canvas, cols, rows int, minpad vg.Length) [][]draw.Canvas
```

Questions:

* Should we add something like this at all?
* Is the API correct?
* Do we need padding at all?
* Would exact padding (rather than minpad) be better? Or maxpad? Or...?
* Do we want separate x/y padding?
* Do we want to provide padding around the edges (as opposed to having the caller crop before calling Grid)?

It's obviouslyy possible to go nuts with knobs on this kind of API. Every knob makes it harder to implement, debug, and use, though. What I wrote above is what I wanted, just now, to add decent-looking subplots to my canvas. I have it implemented locally (although using exact padding instead of minpad to start with, because it is simpler).

**Comment by kortschak** [comment]
Is [this](https://godoc.org/gonum.org/v1/plot#Align) what you want?

**Comment by josharian** [comment]
Hmmm. Looks like that could have saved me a bunch of time this morning. :/

I think this is closer to what I was looking for:

https://godoc.org/gonum.org/v1/plot/vg/draw#Tiles

Although it doesn't do the snap-to-pixel thing that I would hope for.

Anyway, yes, thanks.

**Comment by sbinet** [comment]
FYI, I have built on top of `draw.Tiles` something along what you talk about:

- https://github.com/go-hep/hep/tree/master/hplot#tiles-of-1d-histograms
- https://github.com/go-hep/hep/tree/master/hplot#subplots
