### ISSUE TITLE
vg/svg: due to regressions, cancel PR #520 using styles for svg compactness

### ISSUE THREAD

**Issue by chmike** [gonum/plot#524]
I discovered three regressions resulting from the use of \<style\> in svg plots to reduce svg size.

The first regression is that the image viewer of Gnome ("Eye of Gnome") can’t display the plots. It displays the image as a black rectangle. 

The second regression is that imgur, an image sharing site, display the svg plots as black rectangles. I guess they use the same lib as eye of Gnome to render svg (librsvg).

The third regression is that Inkscape can’t interpret the styles and show a plot as a black rectangle. It is thus not possible to view, edit or annotate the plots with Inkscape. I don’t know the status with Adobe Illustrator.

I thus suggest to cancel the PR #520 which added the styles for compactness.

**Comment by kortschak** [comment]
Confirmed. Nautilus also fails to generate thumbnails, presumably for the same reason.

**Comment by sbinet** [comment]
perhaps this issue should be reported upstream(s) ?

**Comment by chmike** [comment]
Some how the issue of librsvg was raised to the librsvg developper team. The solution is to remove the svgID and move the \<style\> block in front of the file. Inkscape can open and edit the svg. 
The discussed issue is here: https://gitlab.gnome.org/GNOME/librsvg/issues/428

Do I refactor the code to match these requirements, or do we live plot as is ? 

I saw that with more realistic plots, the size saving is not big. Note also that to write the \<style\> block in front, we have to bufferize the data while building the class table.
