### ISSUE TITLE
Debugging errors

### ISSUE THREAD

**Issue by snwfdhmp** [gonum/plot#531]
### You should not panic(err) 

https://github.com/gonum/plot/blob/81bd881d6c80288972ad37334b4863fec6f379fa/plotter/boxplot_test.go#L45-L48

Hey dude,

Just a friendly advice. Use [error logging package like this](https://github.com/snwfdhmp/errlog) for debugging your errors. Debug your code with :

1. Clear stack trace
2. Failing func call highlighting

Real better than panic-ing (in most case). You can still force exit if you need it.

<img width="999" alt="example" src="https://user-images.githubusercontent.com/23099246/53098953-11310c80-3525-11e9-8f6f-302791743cdf.png">

It’s way more easier then to debug. I would be happy to get your feedbacks.

**Comment by sbinet** [comment]
Salut,

it's an example showing the API of gonum/plot, not an example on how to properly handle errors.
besides, `panic`s do provide a clear stack trace :)
we might consolidate examples ones the new `xerrors` package from golang.org/x... ships out (or directly the new errors one from "Go2") but that's a discussion we'll have when these packages are on the table.

**Comment by sbinet** [comment]
closing this but feel free to continue the discussion on the gonum-dev mailing list.

**Comment by sbinet** [comment]
also: `Gonum` is a BSD-3 licensed project. GPL is a no Go.

**Comment by snwfdhmp** [comment]
Thank you for the tip about the License, I don't much much about it. I've made more research and updated it to MIT now.

May I know why "GPL" is a no Go (I appreciate the joke :)) ? Is that specific to your project or a generic point of view ?

**Comment by sbinet** [comment]
Because of the default mode go links (statically) it has bad interferences with how the gpl works and spreads through a given project.

**Comment by snwfdhmp** [comment]
Ok, didn't know that. Thanks fort the tip !
Hope my package can help you in further projects development :) If not I would be happy to receive your feedbacks and refactor some parts/add some features.
