### ISSUE TITLE
plotter: BarChart draws semi-transparent colors grey

### ISSUE THREAD

**Issue by Gaboose** [gonum/plot#550]
### What are you trying to do?
Set a semi-transparent color to a barchart.

### What did you do?

```go
func main() {
	p, _ := plot.New()
	rand.Seed(int64(0))
	v := make(plotter.Values, 20)
	for i := range v {
		v[i] = float64(rand.Intn(20))
	}
	barChart, _ := plotter.NewBarChart(v, 8)
	barChart.Color = color.RGBA{R: 255, G: 255, B: 0, A: 128}
	p.Add(barChart)
	p.Save(4*vg.Inch, 4*vg.Inch, "out.png")
}
```

### What did you expect to happen?

Yellow bars like this to be produced, only a little less bright:
![out](https://user-images.githubusercontent.com/1573047/56938991-79f9be00-6b40-11e9-8611-2dd2c3740550.png)

### What actually happened?

Grey bars:
![out](https://user-images.githubusercontent.com/1573047/56939026-b0cfd400-6b40-11e9-9ceb-8c92c36faeff.png)

### What version of Go and Gonum/plot are you using?

```
go version go1.12.2 linux/amd64
$ echo (cd (go env GOPATH)/src/gonum.org/v1/plot; and git rev-parse HEAD)
3a5f52653745fa15b552c97e1d8052e496e85503
```

### Does this issue reproduce with the current master?
`3a5f52653745fa15b552c97e1d8052e496e85503` is master

**Comment by sbinet** [comment]
try with:

```diff
--- ./main.go.old	2019-04-30 09:50:12.042685394 +0200
+++ ./main.go.new	2019-04-30 09:49:52.872685744 +0200
@@ -17,7 +17,7 @@
 		v[i] = float64(rand.Intn(20))
 	}
 	barChart, _ := plotter.NewBarChart(v, 8)
-	barChart.Color = color.RGBA{R: 255, G: 255, B: 0, A: 128}
+	barChart.Color = color.NRGBA{R: 255, G: 255, B: 0, A: 128}
 	p.Add(barChart)
 	p.Save(4*vg.Inch, 4*vg.Inch, "out.png")
 }
```

**Comment by Gaboose** [comment]
that works! thanks!
