### ISSUE TITLE
cannot import gonum.org/v1/plot 

### ISSUE THREAD

**Issue by haoel** [gonum/plot#558]
### What are you trying to do?

```
import "gonum.org/v1/plot"
```

### What did you do?

```
go get gonum.org/v1/plot 
```

### What actually happened?

404 not found!

Update failed for gonum.org/v1/plot: https://gonum.org/v1/plot Not Found

### What version of Go and Gonum/plot are you using?
```
$ go version
go version go1.11.5 darwin/amd64
```

**Comment by kortschak** [comment]
Can you please post the complete output resulting from this error. With what you have there I don't think we can do anything.

Note that godoc.org is able to refresh, and I am able to `curl` the page that holds the metatags. So this is not something that is happening at our end.

**Comment by haoel** [comment]
Sorry, this is false alarm. I identified the reason is my network problem - China Great Firewall causes this problem. After I connect a VPN, everything goes fine.

**Comment by kortschak** [comment]
Yes, that is common.
