### ISSUE TITLE
plotter: add a way to add labels in canvas coordinates

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#568]
adding text via the [plotter.Labels](https://godoc.org/gonum.org/v1/plot/plotter#Labels) type is great.

but `plotter.Labels` takes labels in "plot" coordinates (_ie:_ `plotter.XY` coordinates).
it's great when one wants to drive the position of the label from the data point of view.

but at times, it's handy to put a label at a fixed position w/o having to know anything about the data (_e.g.:_ I want to write text at `(2/3*xmax, 1/3*ymax)`)
for this, it would be great to give coordinates in the canvas space (_ie:_ `vg.Point{X,Y}`).

**Comment by ctessum** [comment]
I think you can just use https://godoc.org/gonum.org/v1/plot#Plot.Transforms
 or https://godoc.org/gonum.org/v1/plot#Plot.DataCanvas, but it's kind of
tricky so it could be good to have an example.

**Comment by sbinet** [comment]
I may be completely confused, but it seems to me like the methods you are pointing to are dealing with ("plot space" -> "canvas space") transforms.
what I was hinting at was to bypass this completely and give directly text coordinates in "canvas space".

essentially, this is just a `plotter.Labels`-like API (with `vg.Points`) that uses `vg.Canvas.FillText`.

**Comment by ctessum** [comment]
Can you do something like:

da = p.DataCanvas(dc)
da.FillString("x", vg.point{x,y})

**Comment by sbinet** [comment]
see https://github.com/gonum/plot/pull/621.
