### ISSUE TITLE
legend crosses chart

### ISSUE THREAD

**Issue by LazarenkoA** [gonum/plot#569]
Hey. How can I set the height of the columns so that they do not intersect with the chart?

![image](https://user-images.githubusercontent.com/15386101/71559718-b6d0d880-2a72-11ea-9d4d-4203d5161aa1.png)

**Comment by kortschak** [comment]
Alter the `.Y.Max` to be larger than your maximum value so that there is room for the legend.

Please take questions to https://groups.google.com/forum/#!forum/gonum-dev.
