### ISSUE TITLE
Cannot draw plot to in-memory image by following the demo code in wiki.

### ISSUE THREAD

**Issue by AllenDang** [gonum/plot#570]
### What are you trying to do?
Write plot to in-memory image.

### What did you do?
```
        rand.Seed(int64(0))

	p, err := plot.New()
	if err != nil {
		panic(err)
	}

	p.Title.Text = "Plotutil example"
	p.X.Label.Text = "X"
	p.Y.Label.Text = "Y"

	err = plotutil.AddLinePoints(p,
		"First", randomPoints(15),
		"Second", randomPoints(15),
		"Third", randomPoints(15))
	if err != nil {
		panic(err)
	}

	// Draw the plot to an in-memory image.
	img := image.NewRGBA(image.Rect(0, 0, 400, 300))
	c := vgimg.NewWith(vgimg.UseImage(img))
	p.Draw(draw.New(c))

	// Save the image.
	f, err := os.Create("test.png")
	if err != nil {
		panic(err)
	}
	if err := png.Encode(f, img); err != nil {
		panic(err)
	}
	if err := f.Close(); err != nil {
		panic(err)
	}

	// Save the plot to a PNG file.
	 if err := p.Save(4*vg.Inch, 4*vg.Inch, "points.png"); err != nil {
	       panic(err)
	}

```

### What did you expect to happen?
Two output files have same plot.

### What actually happened?
Only points.png has the plot,  test.png is pure white.

### What version of Go and Gonum/plot are you using?
go version: go version go1.13.5 darwin/amd64
Gonum/plot: ca91d9d40d0a39380a55109c45269a2462d2b5b6

### Does this issue reproduce with the current master?
Yes.

**Comment by sbinet** [comment]
I've filed https://github.com/gonum/plot/issues/571.
and pushed #572 (with two examples on how to achieve what you wanted).

that said, we may have a bug lurking somewhere, and as a result passing the `img` around is ineffective.

@kortschak WDYT?

**Comment by AllenDang** [comment]
@sbinet Thanks for your help. I'm using imgui to create a dashboard for chart, so I need to create a RGBA image and use it as a opengl texture to display it.

**Comment by kortschak** [comment]
It'd be helpful is a complete reproducer were posted.

**Comment by kortschak** [comment]
https://play.golang.org/p/bQtZ_FGUP92

It's unclear to me why the `image.Image` that's been passed in is not mutated. It should be as far as I can see, and it's surprising that it's not. I think this needs resolution. The approach at #572 works, but that is not enough.

**Comment by sbinet** [comment]
no. it's not that we wrap the image.

it's because `gg` copies the image we pass as a context:
- https://github.com/fogleman/gg/blob/master/context.go#L88..L113
- https://github.com/fogleman/gg/blob/master/util.go#L79..L84

`gg` works in terms of `image.RGBA` (probably for performance reasons?).
when given an `image.Image` it copies it into a new `image.RGBA`.

we could use `gg.NewContextForRGBA`, but it takes an `*image.RGBA`...

**Comment by kortschak** [comment]
Just documenting is fine.
