### ISSUE TITLE
go.dev can't parse the LICENSE file

### ISSUE THREAD

**Issue by ninedraft** [gonum/plot#578]
### What are you trying to do?
Read documentation of package on pkg.go.dev

### What did you do?

Opened project page: https://pkg.go.dev/mod/gonum.org/v1/plot

### What did you expect to happen?

Documentation and README preview

### What actually happened?

![изображение](https://user-images.githubusercontent.com/12481320/74335730-e67f3a00-4dad-11ea-8693-d61f45791a3a.png)
![изображение](https://user-images.githubusercontent.com/12481320/74335767-f860dd00-4dad-11ea-9808-2a9271e84c99.png)

### What version of Go and Gonum/plot are you using?

![изображение](https://user-images.githubusercontent.com/12481320/74335814-0d3d7080-4dae-11ea-9531-3755ab411b86.png)

### Does this issue reproduce with the current master?
Yep.

### Possible solution
Copy LICENSE content from https://github.com/gonum/license.

**Comment by kortschak** [comment]
Thank you for the report. I have sent a change.
