### ISSUE TITLE
Save() is not saving image to a file

### ISSUE THREAD

**Issue by YerongLi** [gonum/plot#588]
Hi, I am trying to test the first example on the [wiki](https://github.com/gonum/plot/wiki/Example-plots)

    // ....
    func main() {
	    // Save the plot to a PNG file.
	    if err := p.Save(4*vg.Inch, 4*vg.Inch, "points.png"); err != nil {
		    panic(err)
	    }
    }
While the **.Save()** function is not creating file **"points.png"**, anyone met a similar issue?

**Comment by kortschak** [comment]
You are more likely to get a response to questions by posting to https://groups.google.com/forum/#!forum/gonum-dev, preferably with a complete reproducer and the error output.

**Comment by sbinet** [comment]
tentatively closing as invalid.
