### ISSUE TITLE
plot: allow to specify axis label text position

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#589]
This was raised in go-hep/hep#613 (item `3)`).

the feature request was to be able to, say, put the X-axis label text at the far right of that axis (not unlike the plot attached in go-hep/hep#612)

(implementing this directly in `go-hep/hplot` would probably mean duplicating a fair bit of `gonum/plot` code for `Axis`)

I'd propose to add a new field to `Axis.Label`:
```go
type Axis struct {
    Label struct {
        Text string
        Pos draw.Position // or Position draw.Position ?
        draw.TextStyle
    }
}
```

with:
```go
package draw

type Position int
const (
    PosCenter Position = 0
    PosLeft   Position = -10 // is this really needed?
    PosRight  Position = +10
    PosBottom Position = -20 // ditto?
    PosTop    Position = +20
)
```

what do you think?

**Comment by sbinet** [comment]
see https://github.com/gonum/plot/pull/595 for what it could look like.

**Comment by dp1140a** [comment]
Would this allow me to draw a Cartesian grid?  As in my axis can be positioned to cross in the middle of my image or anywhere I specify?  Or as some people like to call it a Rectangular orthogonal coordinate plane with axes X and Y on squared grid?
![blank-cartesian-coordinate-system-in-two-dimensions-rectangular-orthogonal-coordinate-plane-with-axes-x-and-y-on-squared-grid-math-scale-template-2J8R36X](https://github.com/user-attachments/assets/fde48e84-2e2c-4863-8e70-9d340a91d349)

If not any tips or examples on how to do so? Or is it even possible?

**Comment by sbinet** [comment]
no, it "just" allows to translate the axis label, not how the axes are laid out:

![image](https://github.com/user-attachments/assets/c2c6dfdc-8580-4bfe-a16e-46d6b8cc80e7)

**Comment by dp1140a** [comment]
looking at some of the code it seems that this should be possible to implement:

[https://github.com/gonum/plot/blob/9b8e196748f157bb608ba15ff0f69b91f76caaf3/plot.go#L168-L169](https://github.com/gonum/plot/blob/9b8e196748f157bb608ba15ff0f69b91f76caaf3/plot.go#L168-L169)

Would need an additional option on Axis that would place it:
For X-Axis:

- Top
- Middle
- Bottom -- default

For Y-Axis:

- Left -- default
- Center
- Right

Thoughts??
