### ISSUE TITLE
plot: add a Padding field to plot.Axis.Label

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#596]
this was raised here: https://github.com/go-hep/hep/issues/620 by @rmadar 

---

This one is probably for `gonum/plot`. I would find useful to be able to set some padding between an axis label and its axis, as for `hplot.Title`. One can see on the plot below, that it would gain in clarity - I think. More precisely:
```go
p := hplot.New()
p.Title.Padding = 20        // possible 
p.X.Tick.Label.Padding = 10 // doesn't exist yet?
```

![image](https://user-images.githubusercontent.com/30081646/78680866-50b6e580-78ec-11ea-8e03-37b66c205dba.png)

---

**Comment by kortschak** [comment]
What is the difference between the output of what is proposed and the current behaviour?

**Comment by sbinet** [comment]
see https://github.com/gonum/plot/pull/600 for examples w/ padding=0 (what we have currently, still the default with that PR), padding=5 and padding=10.

**Comment by kortschak** [comment]
OK
