### ISSUE TITLE
vg/draw: Crop should be implemented in terms of vg.Canvas operations

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#597]
in `hplot`, I've added the ability to add "borders/margins" to a `plot.Plot`.
this is done via `plot/vg/draw.Crop`.

this works well for most vg backends but for `vgtex`, it breaks.
I suspect it could probably be addressed if we were to implement `draw.Crop` in terms of `vg.Canvas` operations (_ie:_ `Scale` + `Translate`).

what do you think?

**Comment by kortschak** [comment]
I would like to understand how the failure happens in vgtex. There's a lot of work being done in the workaround that you have for vgtex that is obviously not needed for the other backends. So it would be nice to avoid that if possible,

**Comment by sbinet** [comment]
actually... (thanks for being my remote rubber duck).

I if keep the workaround of painting an empty rectangle the size of the original canvas and then use the regular `draw.Crop`, the PDF comes out with the proper border margins.
so it's pgf/tikz's feature (automatically adjusting the bounding box) that was in the way.

see:
- https://github.com/go-hep/hep/pull/625

not sure whether we'd need to add that workaround in `vg/vgtex` proper.

(closing as invalid.)
