### ISSUE TITLE
modules: go.mod updated unexpectedly

### ISSUE THREAD

**Issue by ShawnROGrady** [gonum/plot#611]
### What are you trying to do?
I'm using this library to plot the output of a benchmark run (called `benchplot`, [source code](https://github.com/ShawnROGrady/benchplot)). From within another go project this is run as: `go test ./... -run xxx -bench . | benchplot`

### What did you do?
The bare minimum to reproduce is to create a test module containing only `go.mod`:
```
module github.com/ShawnROGrady/foo

go 1.14

require (
        github.com/ajstarks/svgo v0.0.0-20200320125537-f189e35d30ca // indirect
        github.com/jung-kurt/gofpdf v1.16.2 // indirect
        golang.org/x/image v0.0.0-20200430140353-33d19683fad8 // indirect
        gonum.org/v1/plot v0.7.0
)
```
 `go.sum`, and a basic `main.go`:

```
package main

import (
	"fmt"

	_ "gonum.org/v1/plot"
)

func main() {
	fmt.Println("foo")
}
```

### What did you expect to happen?
I should be able to build the above example (using `go build`) then run it in a different go module without anything being changed. 

### What actually happened?
Running the compiled binary from within a go module results in `go.mod` and `go.sum` being unexpectedly updated in that module. Specifically the following line is added to `go.mod`:
```
gonum.org/v1/plot v0.7.0 // indirect 
```

### What version of Go and Gonum/plot are you using?

```
% go version
go version go1.14.2 darwin/amd64
```

Using go modules, so not seeing anything in `$(go env GOPATH)/src/gonum.org`, but in my `go.mod` I've been able to reproduce with `gonum.org/v1/plot v0.0.0-20200212202559-4d97eda4de95` and `gonum.org/v1/plot v0.0.0-20200212202559-4d97eda4de95` and `gonum.org/v1/plot v0.7.0`

### Does this issue reproduce with the current master?
Yes.

**Comment by kortschak** [comment]
This is expected behaviour, but more significantly this is go tool chain behaviour, and not really anything to do with us. If there is a go.mod file it will have its contents updated to reflect the dependencies the code has.

**Comment by ShawnROGrady** [comment]
@kortschak:

1. `go.mod` isn't empty, either in the module importing this library or the directory where the compiled binary is run. Maybe I should have clarified that when describing my minimal reproduction case
2. the same issue doesn't happen if I recreate that minimal example using the [assert](https://godoc.org/github.com/stretchr/testify/assert) library.

**Comment by ShawnROGrady** [comment]
@kortschak just a quick update, I tried forking and it seems like this is caused by the `initFontDirs()` function in `vg/font_syscall.go` (called in an `init()` function). The issue no longer appears in that minimal example in the original issue If I comment out the `build.Import()` stuff for:
```
// InitFontDirs returns the initial value for the FontDirectories variable.
func initFontDirs() []string {
	dirs := filepath.SplitList(os.Getenv("VGFONTPATH"))

	/*
		if pkg, err := build.Import(importString, "", build.FindOnly); err == nil {
			p := filepath.Join(pkg.Dir, "fonts")
			if _, err := os.Stat(p); err == nil {
				dirs = append(dirs, p)
			}
		}
	*/

	if len(dirs) == 0 {
		dirs = []string{"./fonts"}
	}

	return dirs
}
```

Obviously that isn't a solution, but does highlight the source of the issue

**Comment by kortschak** [comment]
The minimal reproducer you posted has the `go.mod` file empty. Can you post a mininal reproducer that reproduces your bug.

**Comment by kortschak** [comment]
Also note that this is still working as expected and is an effect of the go build chain, not our code.

**Comment by sbinet** [comment]
That said, we could probably migrate to 'x/tools/go/packages' (instead of go/build) that has better Go modules support.

**Comment by sbinet** [comment]
see #612 

on further inspection, it also looks like this code isn't necessary anymore (as the embedded fonts are a real package now...)

fonts handling could also be revamped (_e.g.:_ especially to be able to handle strings with characters with different weights (normal, bold, italics, ...))

**Comment by ShawnROGrady** [comment]
@kortschak updated my original issue to include `go.mod`

**Comment by kortschak** [comment]
Thanks.
