### ISSUE TITLE
Is it possible to create an area chart ?

### ISSUE THREAD

**Issue by ClementVermeer** [gonum/plot#626]
Hello everybody,

I would like to generate an area chart with that library, but I haven't seen any possibilities to make it so far.
Is there any other way to create an area chart with that library ? Otherwise, is there any other go library I could use to do so ?

**Comment by ClementVermeer** [comment]
hello sbinet,

What I call an area chart is this chart : 
![image](https://user-images.githubusercontent.com/54906070/84356850-122bf880-abc5-11ea-97b0-fb9a598f21f1.png)

**Comment by sbinet** [comment]
thanks.

ok, indeed, there isn't such a thing readily available - even if I did something relatively similar for histograms in [hplot](https://github.com/go-hep/hep/tree/master/hplot#stack-of-1d-histograms):
![stack](https://github.com/go-hep/hep/raw/master/hplot/testdata/hstack_golden.png)

presumably, something along these lines could be done with the `plotter.Line` (no pun intended) type:
https://github.com/gonum/plot/blob/master/plotter/line.go#L34

do you want to give it a try?
(I'd imagine creating a new plotter type, _e.g._ `LineStack` that would be, basically, a `[]Line`)

**Comment by ClementVermeer** [comment]
Thanks sbinet ! Your solution is not a real area chart, but maybe handling histograms as you did look good.
So, I will try to make it with plotter.Line as well. I'll keep you updated.

**Comment by sbinet** [comment]
sure, `hstack` isn't an area chart, I was just pointing the similarity (I think) b/w what I did for stacks of histograms and what (I think) could be done w/ Line to achieve an area chart.

feel free to ask questions about the `plotter.LineStack` implementation if you ever get stucked.

**Comment by sbinet** [comment]
closing this old issue.
(feel free to reopen otherwise.)
(or post a link to your new area chart plotter :))
