### ISSUE TITLE
vg: consider adding a Gio-backed canvas

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#627]
`x/exp/shiny` seems... not particularly maintained.

but there is a new kid in town: [Gio](https://gioui.org).
and @ajstarks just created a canvas API on top of that:
- https://github.com/ajstarks/giocanvas

(it'd be great to also have some kind of plot interactivity built on top of that...)

- [x] Gio support for affine transforms (translate,rotate,scale)
- [x] Gio support for stroke path
- [x] Gio support for arc path component
- [x] Gio support for dash-lines
- [ ] integrate w/ Gio fonts handling

![img](https://github.com/ajstarks/giocanvas/raw/master/apisheet.png)

**Comment by kortschak** [comment]
Agreed!

**Comment by sbinet** [comment]
Update: Gio is missing a few things just yet (I have added that list to the issue).

in the meantime, one could do the same trick than what I did for `x/exp/shiny`: draw the plot using `vg/vgimg` and display the resulting image in the Gio window.
it wouldn't be as fast as with direct Gio (which IIUC is GPU-accelerated) though.

**Comment by ajstarks** [comment]
FYI, giocanvas has a not-quite working version of arcs: https://github.com/ajstarks/giocanvas/blob/master/giocanvas.go Lines 522-586

**Comment by sbinet** [comment]
here is what it could look like:
- https://github.com/go-hep/exp/pull/9

**Comment by kevinschoon** [comment]
I recently started work on a toy project to do interactive plotting [here](https://github.com/kevinschoon/qviz). Currently it just writes the resulting plot to a file which is monitored by another program, but Gio would be welcomed addition for native support. By _interactive_ I'm referring to the modify->display feedback cycle, not interactivity of the plot itself.

**Comment by kortschak** [comment]
>By *interactive* I'm referring to the modify->display feedback cycle, not interactivity of the plot itself.

Both of these are very valuable.

**Comment by sbinet** [comment]
so, would the submission of a `vg/vggio` (? or `vg/vgio`?) backend using `vg/vgimg` to paint canvas as a (hopefully) temporary work around, be a well received PR?

having used my `x/exp/vgshiny` for some time and now my `x/exp/vggio` for a couple of days, the latter seems much smoother in redrawing things (at least on my machine), even via that hacky scaffolding.

**Comment by kortschak** [comment]
I think so.

**Comment by sbinet** [comment]
since `e7bc1a4` Gioui exposes affine transforms (rotate,scale,...).
I've started a "real" implementation using this API:
https://github.com/gonum/plot/compare/master...sbinet-gonum:vg-gio

not ready yet but it's starting to look somewhat ok. (if you don't need to draw any line, that is...)

**Comment by sbinet** [comment]
with `7054ba6`, Gioui implements an "arc" path component.

**Comment by sbinet** [comment]
with `33c5fb6`, Gioui implements a basic stroked path API.

**Comment by sbinet** [comment]
dashed lines aren't implemented yet, but it's starting to come quite nicely together (if I may say so myself)
(the legend labels seem a bit akward)

![func_golden](https://user-images.githubusercontent.com/1070920/98705428-fef0a500-237d-11eb-9269-ef633832bb46.png)

**Comment by sbinet** [comment]
and.... dashing paths are _almost_ in. (PR in flight upstream.)

here is what it looks like:
![out](https://user-images.githubusercontent.com/1070920/99104302-272c0e00-25e1-11eb-9dc7-06f3e9fbdad6.png)

versus the equivalent `vg/vgimg`:
![foo](https://user-images.githubusercontent.com/1070920/99104444-488cfa00-25e1-11eb-9ad7-129072a398e0.png)

**Comment by sbinet** [comment]
with `e71bf13`, Gio has dashed stroked paths.
