### ISSUE TITLE
volcano example does not compile

### ISSUE THREAD

**Issue by djadala** [gonum/plot#638]
https://github.com/gonum/plot/blob/e9d75d9287226c92c4bf758e99bc992d419251f4/plotter/volcano_example.go#L45

may be fix is to replace
```go
for l := 100.5; l < volcano.Matrix.(*mat.Dense).Max(); l += 5 {
```
with
```go
for l := 100.5; l < mat.Max( volcano.Matrix); l += 5 {
```

**Comment by sbinet** [comment]
right.

do you want to send a PR for this?

**Comment by kortschak** [comment]
I'll fix it, it's my mess.

**Comment by sbinet** [comment]
thanks @djadala for the report.

**Comment by djadala** [comment]
> thanks @djadala for the report.

You’re welcome
