### ISSUE TITLE
vg/vggio: use of os.Exit in tests in not allowed

### ISSUE THREAD

**Issue by kortschak** [gonum/plot#643]
On Go master use of `os.Exit` is not allowed resulting in a failure in the vg/vggio test.
```
=== RUN   ExampleCanvas
panic: unexpected call to os.Exit(0) during test

goroutine 21 [running]:
os.Exit(0x0)
	/home/travis/.gimme/versions/go/src/os/proc.go:68 +0x6d
gonum.org/v1/plot/vg/vggio_test.ExampleCanvas.func1(0x4081b76eddbb76ee, 0x407a93264c993265)
	/home/travis/gopath/src/gonum.org/v1/plot/vg/vggio/vg_example_test.go:63 +0x5d8
created by gonum.org/v1/plot/vg/vggio_test.ExampleCanvas
	/home/travis/gopath/src/gonum.org/v1/plot/vg/vggio/vg_example_test.go:31 +0x51
FAIL	gonum.org/v1/plot/vg/vggio	0.054s
```
It's not entirely clear to me how to avoid this problem; `app.Main` blocks, so the use of `os.Exit(0)` to terminate a gioui application is idiomatic, and doing something clever to allow the program to terminate (panic and recover or run `app.Main` in a separate goroutine and wait on a termination channel/lock) would give the wrong direction to users looking for how to do things the right way.

I think that possibly the best solution (not a good one though) would be to remove the `// Output:` comment and duplicate the tests source with one of the workarounds above so that we have testing code and documentation code.

/cc @sbinet

**Comment by sbinet** [comment]
yep, that's what I did in my `vg-gio` branch (the one that "really" uses the Gio features)

in the test functions, I think we can use the `gioui.org/app/headless` package which is useful to create, say, .png files, sans the `app.Main` dance.
