### ISSUE TITLE
How to cancel the fit the range of the data.

### ISSUE THREAD

**Issue by vintingb** [gonum/plot#644]
## How to cancel the fit the range of the data.
In file [plot.go](https://github.com/gonum/plot/blob/master/plot.go) lines 123
if necessary to fit the range of the data.

**Comment by sbinet** [comment]
you can set by hand the min/max values of the plot's axes after having added the plotters.
wouldn't that work?

**Comment by vintingb** [comment]
In fact, I did the same, but the straight line I wanted does not appear on the picture, no matter how I modify the order

**Comment by vintingb** [comment]
> you can set by hand the min/max values of the plot's axes after having added the plotters.
> wouldn't that work?

In fact, I did the same, but the straight line I wanted does not appear on the picture, no matter how I modify the order

**Comment by kortschak** [comment]
Can you paste the code you are having difficulties with, along with the output please.

**Comment by vintingb** [comment]
> Can you paste the code you are having difficulties with, along with the output please.

[mycode](https://play.golang.org/p/3HoJ1vxoK1N)
