### ISSUE TITLE
plot: saved file missing data points

### ISSUE THREAD

**Issue by fredcarle** [gonum/plot#645]
### What are you trying to do?
Save plot as PNG

### What did you do?

I created a simple line plot.

### What did you expect to happen?

The is was I would expect the PNG to show. But it only works in an SVG or PDF format.
![image](https://user-images.githubusercontent.com/4949751/100380859-b4aa2d80-2fe5-11eb-94e6-e0a2623e76be.png)

### What actually happened?

When I try to output the file as PNG, it doesn't draw the full dataset
![image](https://user-images.githubusercontent.com/4949751/100380837-a65c1180-2fe5-11eb-8440-3eb6acb3ad21.png)

### What version of Go and Gonum/plot are you using?

go version go1.14.4 windows/amd64

gonum.org/v1/plot v0.0.0-20190515093506-e2840ee46a6b/go.mod h1:Wt8AAjI+ypCyYX3nZBvf6cAIx93T+c/OS2HFAYskSZc=
gonum.org/v1/plot v0.8.1 h1:1oWyfw7tIDDtKb+t+SbR9RFruMmNJlsKiZUolHdys2I=
gonum.org/v1/plot v0.8.1/go.mod h1:3GH8dTfoceRTELDnv+4HNwbvM/eMfdDUGHFG2bo3NeE=

### Does this issue reproduce with the current master?
haven't tried

**Comment by sbinet** [comment]
might be a duplicate (or a variation) of https://github.com/gonum/plot/issues/559

could you post a minimal reproducer?

thanks.

**Comment by sbinet** [comment]
ping?
