### ISSUE TITLE
Cannot import "gonum.org/v1/plot" package with "go get" command

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [gonum/plot#658]
### What are you trying to do?

Import "gonum.org/v1/plot" package with `go get ` command.

### What did you do?

```
$ go get -v gonum.org/v1/plot
```

### What actually happened?

```
$ go get -v gonum.org/v1/plot
go get gonum.org/v1/plot: unrecognized import path "gonum.org/v1/plot": parse https://gonum.org/v1/plot?go-get=1: no go-import meta tags ()

$ go get -v gonum.org/v1/plot@v0.8.1
go get gonum.org/v1/plot@v0.8.1: unrecognized import path "gonum.org/v1/plot": parse https://gonum.org/v1/plot?go-get=1: no go-import meta tags ()
```

### What version of Go and Gonum/plot are you using?

```
$ go version
go version go1.15.6 linux/amd64
```

**Comment by kortschak** [comment]
This is either a transient thing (we have seen this before in some places) or a result of redirects that we just put in place for documentation. 

I am able to go get gonum.org/v1/plot to a new module after having deleted my download cache.
```
~ $ mkdir plot
~ $ cd plot/
~/plot $ go mod init pf
go: creating new go.mod: module pf
~/plot $ go get -v gonum.org/v1/plot
go get: added gonum.org/v1/plot v0.8.1
~/plot $ cat go.mod 
module pf

go 1.16

require gonum.org/v1/plot v0.8.1 // indirect
```

However, it's worth backing that out the redirects just in case this is what has caused the issue. Please try again soon.

**Comment by kortschak** [comment]
I have reverted the redirects. Please try again now.

**Comment by spiegel-im-spiegel** [comment]
I was able to import gonum.org/v1/plot.

Many thanx!

**Comment by kortschak** [comment]
@spiegel-im-spiegel I have replaced the documentation redirect with a new strategy. Since you were able to get the previous system to fail, but I was not, would you please try again to check that I have not re-broken it. Thanks.
