### ISSUE TITLE
How to draw a table similar to 'matplotlib.pyplot.table', just like this:https://matplotlib.org/3.1.1/gallery/misc/table_demo.html#sphx-glr-gallery-misc-table-demo-py

### ISSUE THREAD

**Issue by Yorkia** [gonum/plot#665]

**Comment by kortschak** [comment]
>If the issue is a question about usage or similar, please ask at the Gonum discussion list rather than filing an issue:

>https://groups.google.com/forum/#!forum/gonum-dev

**Comment by Yorkia** [comment]
> > If the issue is a question about usage or similar, please ask at the Gonum discussion list rather than filing an issue:
> 
> > https://groups.google.com/forum/#!forum/gonum-dev

sorry, i will close this issue, thanks for your answer

**Comment by Yorkia** [comment]
> > If the issue is a question about usage or similar, please ask at the Gonum discussion list rather than filing an issue:
> 
> > https://groups.google.com/forum/#!forum/gonum-dev

sorry, i will close this issue, thanks for your answer
