### ISSUE TITLE
the bar cover the title

### ISSUE THREAD

**Issue by fengjiansunren** [gonum/plot#673]
![image](https://user-images.githubusercontent.com/7437021/108945348-6d404580-7697-11eb-914f-944ca32c0687.png)

how to solve this problem?

**Comment by sbinet** [comment]
Thanks for the report.

Could you provide a small snippet of (self contained) code that reproduces this issue?

Thanks a lot.

**Comment by sbinet** [comment]
ping?
(I think this should be fixed w/ https://github.com/gonum/plot/pull/708 but it's hard to say without code to try out)

**Comment by sbinet** [comment]
I'll mark this as (probably) fixed by #708.
