### ISSUE TITLE
plotter: Cannot set fill color on BoxPlot

### ISSUE THREAD

**Issue by rogerwelin** [gonum/plot#674]
### What are you trying to do?
Trying to set a FillColor on the BoxPlot struct after creating a new BoxPlot

### What did you expect to happen?
To be able to set a fill color on the boxplot (just like how Histogram works)

### What actually happened?
There seem's to be no field in the BoxPlot struct to set the color of the box 

### What version of Go and Gonum/plot are you using?
go version go1.15.6 darwin/amd64
gonum.org/v1/plot v0.8.1

### Does this issue reproduce with the current master?
Yes

**Comment by sbinet** [comment]
right.
it seems relatively easy to add.

do you want to take a stab at it?

steps:
- add a field to BoxPlot to control the fill color (default: `nil`, for backward compatibility) https://github.com/gonum/plot/blob/master/plotter/boxplot.go#L67
- handle a non-`nil` value for that `color.Color` `FillColor` field in the `Plot` method https://github.com/gonum/plot/blob/master/plotter/boxplot.go#L216
- ditto for the horizontal box plot variant.

**Comment by rogerwelin** [comment]
Thanks for the hints @sbinet 
I've opened up PR #675

**Comment by rogerwelin** [comment]
@sbinet Done, see: https://github.com/gonum/plot/wiki/Example-plots#box-plots

**Comment by sbinet** [comment]
ah, right.

well, I was actually thinking about these:
- https://github.com/gonum/plot/blob/master/plotter/boxplot_example_test.go#L18

apologies for the confusion.

**Comment by rogerwelin** [comment]
Aha, that will require me to update the "golden images" as well otherwise the boxplots test will fail. I'll update with a new commit this evening
