### ISSUE TITLE
How can I support Cartesian coordinates ？

### ISSUE THREAD

**Issue by MarkZhou123** [gonum/plot#713]
![image](https://user-images.githubusercontent.com/13870924/124761442-63432300-df64-11eb-8eb6-b957e44ea9dd.png)

how can I do to support the above style?

**Comment by kortschak** [comment]
[spatial/r2](https://pkg.go.dev/gonum.org/v1/gonum/spatial/r2), but questions should be asked on [gonum-dev](https://groups.google.com/g/gonum-dev).
