### ISSUE TITLE
Will plot support the Organizational Chart?

### ISSUE THREAD

**Issue by elin72215** [gonum/plot#714]
I try to find a golang module to draw an Organizational Chart.
But I can't find it in Wiki examples.

Will plot support the Organizational Chart?

Or, is there a way to show some texts at the middle place of the square drawn by plot?

**Comment by sbinet** [comment]
hi,

do you mean this type of chart?
![img](https://upload.wikimedia.org/wikipedia/commons/8/86/Departments_in_advertising_agencies.jpg)

I don't think it would make sense to host it in gonum/plot proper, but we could definitely add a link to a package _using_ `gonum/plot` to draw this kind of thing.

alternatively, you could look at [`gonum/graph`](https://pkg.go.dev/gonum.org/v1/gonum/graph) as a graph description layer (and perhaps use `dot` to display it).

**Comment by sbinet** [comment]
unless you or @kortschak disagree, I'll close this issue in a week.

**Comment by kortschak** [comment]
I don't think this is something we should support. There are many other tools for this kind of thing.
