### ISSUE TITLE
cmpimg: invalid PDF comparison

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#717]
`cmpimg` fails to provide a meaningful comparison for PDF documents:

```go
func cmpPdf(pdf1, pdf2 []byte) bool {
	return fpdf.CompareBytes(pdf1, pdf1, false) == nil
}
```
(it compares `pdf1` to itself)

unfortunately, `fpdf.CompareBytes` just compares bytes (it's a convoluted `bytes.Equal`) so all tests fails when fixing the above bug.

I'd vote for going back to `rsc.io/pdf` to perform the comparison.
yes, it's archived, but the PDF standard won't change anytime soon.
and if we find a bug in `rsc.io/pdf`, we can fork.

(I haven't looked for a replacement of `rsc.io/pdf`.)

**Comment by kortschak** [comment]
SGTM
