### ISSUE TITLE
Set {X,Y } Min,Max，Image distortion , Is there a way like python's "axes.set_aspect('equal')"

### ISSUE THREAD

**Issue by bzl19951110** [gonum/plot#737]
![image](https://user-images.githubusercontent.com/45144990/132280181-58091fef-bdb4-4090-8762-b4d50b8f3358.png)

set after：
![image](https://user-images.githubusercontent.com/45144990/132280139-a0d34dda-5aa8-42f3-b8f1-8665d60304be.png)

**Comment by sbinet** [comment]
There isn't.
But as gonum/plot requires you to provide the 'image.Image' (from which you can easily retrieve the dimensions), it seems easy to implement "user side".

**Comment by sbinet** [comment]
(closing. feel free to reopen if you feel this wasn't properly addressed)
