### ISSUE TITLE
Extra X-axis padding when there is a label

### ISSUE THREAD

**Issue by JAicewizard** [gonum/plot#779]
### What are you trying to do?

Create a graph with 0-padded axis and axis names

### What did you do?
```
package main

import (
	"gonum.org/v1/plot"
	"gonum.org/v1/plot/plotter"
)

type (
	benchmarkSequence struct {
	}
)

func main() {
	p := plot.New()
	p.X.Padding = 0
	p.Y.Padding = 0
	p.X.Label.Text = "P (Passingrate)" // comment this line to get expected result

	line, err := plotter.NewLine(benchmarkSequence{})
	if err != nil {
		panic(err)
	}
	p.Add(line)
	err = p.Save(500, 500, "plotLogo.png")
	if err != nil {
		panic(err)
	}
}

// Implement plot.XYer for benchmarkSequence
func (s benchmarkSequence) Len() int {
	return 99
}

func (s benchmarkSequence) XY(i int) (float64, float64) {
	return float64(i) / 100, float64(i) / 100
}
```
### What did you expect to happen?
![plotLogo](https://github.com/gonum/plot/assets/19241481/acde47ca-b266-4e78-8680-0da29705a433)

### What actually happened?
![plotLogo](https://github.com/gonum/plot/assets/19241481/0190211e-e3df-410b-92c7-c478811de44c)

### What version of Go and Gonum/plot are you using?
I just fetched gonum 0.13, and im using go 1.22.3 (linux/amd64)

### Does this issue reproduce with the current master?
Did not try, but there does not seem to be any real changes in master

**Comment by JAicewizard** [comment]
Actually you can see that with the expected result the Y-axis is also misaligned

**Comment by kortschak** [comment]
It looks to me like the descents should not be being used in calculating the height of the axis. If I do this
```diff
diff --git a/axis.go b/axis.go
index 3b275ad..451acce 100644
--- a/axis.go
+++ b/axis.go
@@ -235,7 +235,6 @@ type horizontalAxis struct {
 // size returns the height of the axis.
 func (a horizontalAxis) size() (h vg.Length) {
        if a.Label.Text != "" { // We assume that the label isn't rotated.
-               h += a.Label.TextStyle.FontExtents().Descent
                h += a.Label.TextStyle.Height(a.Label.Text)
                h += a.Label.Padding
        }
```
I get this
![plotLogo](https://github.com/gonum/plot/assets/275221/c45937ca-5356-440b-852e-4f2177bd9a1e)

@sbinet WDYT?

**Comment by sbinet** [comment]
(apologies for the belated answer. with the events unfolding in France, I have a limited bandwith for software...)

SGTM.
