### ISSUE TITLE
Add Rotation to the text style.

### ISSUE THREAD

**Issue by eaburns** [gonum/plot#78]
Original [issue 51](https://code.google.com/p/plotinum/issues/detail?id=51) created by eaburns on 2012-08-08T18:18:01.000Z:

Both plotter.Labels and tick marks should be able to draw with different rotations, so it might as well go into the text style.

**Comment by aboinameddave** [comment]
Any news on being able to rotate the axis label orientation? This would be useful in combination for time/date labels on the x-axis because these labels are long.

**Comment by eaburns** [comment]
Was this fixed by #227?

**Comment by ctessum** [comment]
To rotate tick marks, it is for example plot.Plot.X.Tick.TextStyle.Rotation

To rotate the axis label, it is for example plot.Plot.X.Label.TextStyle.Rotation

There is an example [here](https://godoc.org/github.com/gonum/plot/plotter#example-package--Rotation); the output given by the example is [here](https://github.com/gonum/plot/blob/master/plotter/testdata/rotation_golden.png).

**Comment by ctessum** [comment]
This issue can probably be closed now, right?

**Comment by eaburns** [comment]
Yes, we can close it.
